### PR TITLE
Make sure all inline alerts have correct styles

### LINKED ISSUE #8044: Make sure all inline alerts have correct styles
### Describe the bug

All the Inline Alert for Kiali is supposed to be one of these styles:
401606090-47a37022-9eec-430e-b984-828d970b0dce

Make sure that all inline alerts in Kiali are consistent with these styles.
Comes from this discussion https://github.com/kiali/kiali/pull/7976#issuecomment-2580623268

### PR DESCRIPTION
**Pull request by mayleighnmyers**
### Describe the change

Making sure that Alerts are mimicking,  https://v5-archive.patternfly.org/components/alert  

AboutUIModal.tsx Before and After (margin needs to be changed):
Before:
image
After:
Screenshot from 2025-01-15 11-17-02

InitializingScreen.tsx
Before:
Screenshot from 2025-01-13 12-08-32
After:
Screenshot from 2025-01-13 12-11-06

WizardLabels.tsx
Before: 
Screenshot from 2025-01-13 12-19-58
(No need to make changes other than margin)
After:
Screenshot from 2025-01-15 11-29-55

NotificationList.tsx
How the alert shows:
Screenshot from 2025-01-13 15-24-16
Removed the isInLine in the code since toast alerts DO NOT use isInLine alerts

TracesComponent.tsx
Before: 
Screenshot from 2025-01-14 11-24-39
After:
Screenshot from 2025-01-14 11-28-28

Closes #8044

### CODE REVIEW

File: frontend/src/components/IstioWizards/WizardLabels.tsx [hunk 1]
```diff
@@ -39,6 +39,15 @@ const clearButtonStyle = kialiStyle({
...
 
+const alertStyle = kialiStyle({
+  marginTop: '1rem',
+  $nest: {
+    '& .pf-v5-c-alert__title': {
+      marginTop: 0
+    }
+  }
+})
+
```
Comment (ferhoyos) [inline frontend/src/components/IstioWizards/WizardLabels.tsx:50]: The $nest part is not needed in the WizardLabels component, only the marginTop to `1rem`. 

```suggestion
const alertStyle = kialiStyle({
  marginTop: '1rem'
})

```

**Review by ferhoyos — CHANGES_REQUESTED** [review]
Good job @mayleighnmyers! Just a small comment, and then we are ready to go!

**Review by ferhoyos — APPROVED** [review]
LGTM
