### PR TITLE
fix: activate inbound and outbound edges when rank is auto enabled in find field

### LINKED ISSUE #5915: Include inbound and outbound edges when automatically activating rank in the graph
When a user wants to use the ranking feature in the graph and for example types a rank query in the find section, if rank is not activated, Kiali will activate it and alert the user about this:

In the following scenario, ranking is not activated:

image

Then, the user types an expression in the find field, using the rank feature:

image

But as a result nothing is highlighted, and I think this is confusing a little bit, because I was expecting something to be highlighted right away. Of course then I checked the docs, and the criteria, but sometimes users do not do this (like the first time I tried this myself :) ). 

This issue is to improve this experience and possibly: 

1. Indicate this in the green alert
2. Activate both inbound and outbound edges in the criteria

### PR DESCRIPTION
**Pull request by sandesh-8622**
Hi, I came across this in the good first issue list and saw it's been open since 2023 and unassigned so I thought I'd try fixing it. Let me know if I missed anything!

### Describe the change

When you type something like `rank = 1` in the find field and rank isn't turned on, Kiali turns it on automatically but nothing actually gets highlighted. The problem is rankBy is empty by default so no edge directions are set and rank values never get calculated. This fix also sets both inbound and outbound edges at the same time and updates the alert message so the user knows what happened.

### Steps to test the PR

1. Open the Graph page
2. Make sure Rank is not enabled in Display settings
3. Type `rank = 1` in the find field
4. Rank should now auto-enable with both inbound and outbound edges selected and nodes should be highlighted

### Automation testing

Updated GraphFind.test.tsx to include the new rankBy and setRankBy props

### Issue reference

Fixes #5915

### CODE REVIEW

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 1]
```diff
@@ -932,8 +934,14 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
         return { target: 'node', selector: { prop: NodeAttr.aggregateValue, op: op, val: val } };
       case 'rank': {
         if (!this.props.showRank) {
-          addSuccess('Enabling "Rank" display option for graph find/hide expression');
+          addSuccess(
+            'Enabling "Rank" display option with inbound and outbound edges for graph find/hide expression'
+          );
           this.props.toggleRank();
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx:940]: **BUG-1: Double-toggle on compound rank expressions**

For a compound expression like `rank = 1 OR rank = 2`, `parseValue` splits on `OR` (line 722) and calls `parseExpression` once per sub-expression (line 733-734). Each `rank` token checks `this.props.showRank`, which reflects the render-time prop — not the post-dispatch Redux state. If `showRank` was initially `false`, both tokens see `false` and both dispatch `toggleRank()`, flipping rank `false → true → false`. Net result: rank ends up **off**.

`setRankBy` is called twice (harmless since it's idempotent), but the double `toggleRank()` silently undoes the auto-enable.

**Suggested fix:** Replace `toggleRank()` with idempotent "ensure enabled" semantics — e.g. a dedicated `enableRank` action, or a local guard flag within a single `parseValue` call to prevent re-entry.

**Severity: Important**

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 2]
```diff
@@ -932,8 +934,14 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
...
+          this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx]: **IMP-1: Overrides previous `rankBy` preference when rank was disabled**

When rank was previously enabled with only one edge direction (e.g. only inbound), then disabled by the user, and later auto-enabled via the find field, this always sets both inbound and outbound, overriding the user's previous preference. This happens because `toggleRank` only flips `showRank` without resetting `rankBy`, so stale values can persist.

A more conservative approach would check if `rankBy` is already populated before overriding:

```typescript
if (!this.props.showRank) {
  this.props.toggleRank();
  if (this.props.rankBy.length === 0) {
    addSuccess('Enabling "Rank" display option with inbound and outbound edges for graph find/hide expression');
    this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
  } else {
    addSuccess('Enabling "Rank" display option for graph find/hide expression');
  }
} else if (this.props.rankBy.length === 0) {
  addSuccess('Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression');
  this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
}
```

**Severity: Low**

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 3]
```diff
@@ -932,8 +934,14 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
...
+        } else if (this.props.rankBy.length === 0) {
+          addSuccess('Enabling inbound and outbound edges for Rank display option');
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx]: **STY-1: Alert message inconsistency**

This message doesn't follow the consistent pattern used by all other auto-enable messages in this file:

- `'Enabling "Security" display option for graph find/hide expression'`
- `'Enabling "Idle nodes" display option for graph find/hide expression'`
- `'Enabling [P95] "Response Time" edge labels for this graph find/hide expression'`

Missing the `"for graph find/hide expression"` suffix and doesn't quote the feature name.

Suggested: `'Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression'`

**Severity: Low**

File: frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx [hunk 4]
```diff
@@ -1,9 +1,8 @@
 import * as React from 'react';
 import { shallow } from 'enzyme';
 import { GraphFindComponent } from '../GraphFind';
-import { EdgeLabelMode, EdgeMode } from 'types/Graph';
+import { EdgeLabelMode, EdgeMode, RankMode } from 'types/Graph';
 import { Controller } from '@patternfly/react-topology';
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx:5]: **STY-2: Blank line removed between imports and code**

A blank line between the import block and the first `const` statement was removed. This is an existing convention in the file — please restore it.

**Severity: Trivial**

File: frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx [hunk 5]
```diff
@@ -30,6 +29,8 @@ describe('Parse find value test', () => {
         toggleGraphSecurity={testHandler}
         toggleGraphVirtualServices={testHandler}
         toggleIdleNodes={testHandler}
+        rankBy={[] as RankMode[]}
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx:33]: **TST-1: No test coverage for the new auto-enable side effects**

The new `rankBy` and `setRankBy` props are wired in so the existing test compiles, but no tests verify the actual new behavior. The existing `rank = 1` test (line 117) only asserts the returned selector shape, which passes identically with or without this fix.

The fixture sets `showRank={true}` and `rankBy={[]}`, which puts it in the new `else if` branch — but with no-op stubs, the branch fires silently and the assertion remains green regardless of whether the side effects execute.

**Missing test scenarios:**
1. `showRank=false`, `rankBy=[]` — verify `toggleRank` and `setRankBy` are called with `[RANK_BY_INBOUND_EDGES, RANK_BY_OUTBOUND_EDGES]`
2. `showRank=true`, `rankBy=[]` — verify `setRankBy` is called but `toggleRank` is not
3. `showRank=true`, `rankBy=[RANK_BY_INBOUND_EDGES]` — verify neither is called (existing preference preserved)
4. Compound expression `rank = 1 OR rank = 2` — verify `toggleRank` is called exactly once (blocked by BUG-1)

**Fix:** Replace `testSetter`/`testHandler` with `jest.fn()` spies for `setRankBy` and `toggleRank` in focused rank tests, and assert call counts and arguments. Also mock `AlertUtils` (`addSuccess` is called in the new branch but not mocked, which could cause noise).

**Severity: Important**

**Comment by sandesh-8622** [comment]
Thanks a lot @jmazzitelli for the detailed review, it really helped me understand the issues better! 
I tried to fix everything you pointed out, the double toggle bug, the rankBy preference issue, the alert messages and added the jest tests. Let me know if I missed anything!

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 6]
```diff
@@ -710,6 +712,7 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
     isFind: boolean
   ): { edgeSelector: SelectOr | undefined; nodeSelector: SelectOr | undefined } => {
     let preparedVal = this.prepareValue(val);
+    let rankAutoEnabled = false;
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx]: **BUG: Guard variable is in the wrong scope — CI compile failure**

This local variable is declared in `parseValue`, but the `case 'rank':` block that references it is inside `parseExpression` — a separate method. The variable is out of scope there, so it has no effect and TypeScript correctly reports `TS6133: 'rankAutoEnabled' is declared but its value is never read`.

The fix needs to use an instance variable so it's shared across `parseValue` (where it's reset) and `parseExpression` (where it's checked and set). For example:

1. Add a class property:
```typescript
private rankAutoEnabled = false;
```

2. Reset it at the start of `parseValue`:
```typescript
this.rankAutoEnabled = false;
```

3. Use `this.rankAutoEnabled` in the `case 'rank':` block inside `parseExpression`:
```typescript
case 'rank': {
  if (!this.props.showRank && !this.rankAutoEnabled) {
    this.rankAutoEnabled = true;
    this.props.toggleRank();
    if (this.props.rankBy.length === 0) {
      addSuccess('Enabling "Rank" display option with inbound and outbound edges for graph find/hide expression');
      this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
    } else {
      addSuccess('Enabling "Rank" display option for graph find/hide expression');
    }
  } else if (this.props.rankBy.length === 0 && !this.rankAutoEnabled) {
    addSuccess('Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression');
    this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
  }
```

This is safe because `parseValue` runs synchronously — the instance variable is reset before each parse and only mutated within the same call stack.

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 7]
```diff
@@ -931,11 +934,20 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
...
+        if (!this.props.showRank && !rankAutoEnabled) {
+          rankAutoEnabled = true;
           this.props.toggleRank();
+          if (this.props.rankBy.length === 0) {
+            addSuccess('Enabling "Rank" display option with inbound and outbound edges for graph find/hide expression');
+            this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
+          } else {
+            addSuccess('Enabling "Rank" display option for graph find/hide expression');
+          }
+        } else if (this.props.rankBy.length === 0) {
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx]: **BUG-1b: Guard flag should also protect the `else if` branch**

Once the scope issue above is fixed, the guard also needs to cover this branch. Otherwise, for `rank = 1 OR rank = 2` with `showRank=false, rankBy=[]`, the second `rank` token bypasses the first branch (correctly) but falls into this `else if` — causing a duplicate `setRankBy` and a second toast.

```suggestion
        } else if (this.props.rankBy.length === 0 && !this.rankAutoEnabled) {
```

File: frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx [hunk 8]
```diff
@@ -643,3 +645,143 @@ describe('Parse find value test', () => {
...
+        toggleGraphSecurity={jest.fn()}
+        toggleGraphVirtualServices={jest.fn()}
+        toggleIdleNodes={jest.fn()}
+        toggleRank={mockToggleRank}
+      />
+    );
+    const instance = wrapper.instance() as GraphFindComponent;
+    // @ts-ignore
+    instance.parseValue('rank = 1 OR rank = 2', true);
+    expect(mockToggleRank).toHaveBeenCalledTimes(1);
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx:785]: **Test: also assert `setRankBy` call count**

Once the guard scope is fixed, assert that `setRankBy` is also called exactly once for compound expressions.

```suggestion
    expect(mockToggleRank).toHaveBeenCalledTimes(1);
    expect(mockSetRankBy).toHaveBeenCalledTimes(1);
```

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 9]
```diff
@@ -931,11 +934,20 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
...
+          addSuccess('Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression');
+          this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
         }
-
+
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx]: **STY-3: Trailing whitespace**

This line has two trailing spaces.

```suggestion

```

**Comment by sandesh-8622** [comment]
Hi @jmazzitelli , I gave it one final try and pushed the fixes, I have made rankAutoEnabled a class property for scope issue. Thanks a lot for the patience and detailed reviews on what changes to make. :>

File: frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx [hunk 10]
```diff
@@ -931,9 +935,18 @@ export class GraphFindComponent extends React.Component<GraphFindProps, GraphFin
...
+          this.rankAutoEnabled = true;
           this.props.toggleRank();
+          if (this.props.rankBy.length === 0) {
+            addSuccess('Enabling "Rank" display option with inbound and outbound edges for graph find/hide expression');
+            this.props.setRankBy([RankMode.RANK_BY_INBOUND_EDGES, RankMode.RANK_BY_OUTBOUND_EDGES]);
+          } else {
+            addSuccess('Enabling "Rank" display option for graph find/hide expression');
+          }
+        } else if (this.props.rankBy.length === 0 && !this.rankAutoEnabled) {
+          addSuccess('Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression');
```
Comment (jmazzitelli) [inline frontend/src/pages/Graph/GraphToolbar/GraphFind.tsx:949]: **Minor: duplicate notification on compound expression when rank is already on**

If a user has rank enabled (`showRank=true`) but both edge direction checkboxes unchecked (`rankBy=[]`), then types `rank = 1 OR rank = 2`, this `else if` branch fires on the first `rank` token and calls `setRankBy` + shows the notification. But unlike the first branch (line 939), it doesn't set `this.rankAutoEnabled = true`. So the second `rank` token enters the same `else if` branch again — calling `setRankBy` a second time (harmless, same values) and showing a duplicate notification.

Fix: set the guard flag here too.

```suggestion
          this.rankAutoEnabled = true;
          addSuccess('Enabling inbound and outbound edges for "Rank" display option for graph find/hide expression');
```
