### PR TITLE
Ensure namespace dropdown is sorted alphabetically

### LINKED ISSUE #7227: Namespace selector order is random
### Describe the bug

Namespace selector ordering is random.

namespaceselector

### Expected Behavior

Namespace selector should be sorted alphabetically.

### What are the steps to reproduce this bug?

1. Open/close namespace selector repeatedly

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: v1.82.0**
- **Istio version:  1.21**
- **Kubernetes impl: vanilla** 
- **Kubernetes version: 1.28** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

Sorts namespaces alphabetically in the dropdown selector.

### Steps to test the PR

Deploy kiali. Repeatedly click the namespace dropdown and ensure the namespaces are always sorted correctly.

### Automation testing

Included with this change.

### Issue reference

Fixes #7227

### CODE REVIEW

File: frontend/src/components/NamespaceDropdown.tsx [hunk 1]
```diff
@@ -193,27 +193,29 @@ class NamespaceDropdownComponent extends React.PureComponent<NamespaceDropdownPr
...
-            type="checkbox"
-            value={namespace.name}
-            checked={!!selectedMap[namespace.name]}
-            onChange={this.onNamespaceToggled}
-          />
-          <span className={optionLabelStyle}>{namespace.name}</span>
-        </div>
-      ));
+      const namespaces = this.filtered()
+        .sort((a, b) => a.name.localeCompare(b.name))
```
Comment (nrfox) [inline frontend/src/components/NamespaceDropdown.tsx:203]: This line is the only actual thing that changed with this PR. The rest was just mandated by the new linter rules.

**Review by jshaughn — APPROVED** [review]
LG! Thanks for adding the test.
