### PR TITLE
Check each cluster individually to see if they are openshift in namespace service

### LINKED ISSUE #7665: Kiali federation with multiple Kubernetes flavors not able to access none OpenShift workloads/applications when running on OCP
### Describe the bug

Using Kiali Federation to access multiple ServiceMesh (istio 1.20.8 and working) does not work showing (at least) applications information with the error

```
{"level":"trace","time":"2024-08-25T19:12:00Z","message":"Access to the server endpoint is not secured with credentials - letting request come in. Url: [https:///api/namespaces/ns8/apps/mockbin?rateInterval=60s&health=true&clusterName=west]"}
{"level":"error","time":"2024-08-25T19:12:00Z","message":"the server could not find the requested resource"}
{"level":"info","time":"2024-08-25T19:12:00Z","message":"Error fetching Namespaces for cluster [west]: projects.project.openshift.io is forbidden: User \"system:serviceaccount:kiali-access-ns:kiali-remote-access\" cannot list resource \"projects\" in API group \"project.openshift.io\" at the cluster scope"}
```

The error isn't ovious as vanilla Kubernetes systems do not have OpenShift specific CRD's like `Project` which seems to be not switched when running the Kiali instance handling the federation on OpenShift. 
The Kiali instance in the vanilla Kubernetes is working fine without any issues.

### Expected Behavior

Handling between various Kubernetes flavors should be consistent through federated clusters.

### What are the steps to reproduce this bug?

1. Install multi-primary on OpenShift and vanilla Kubernetes
2. Federate OCP and vanilla using OCP Kiali as federated instance
3. Select a vanilla Kubernetes resource

### Environment
*Learn about how to determine versions [here](
kiali-multi-vendor-federation
kiali-multi-vendor-graph
kiali-vanilla-application-error).*

- **Kiali version:** 1.73.9 (but also verified with latest)
- **Istio version:** 1.20.8
- **Kubernetes impl:** OCP and Kind k8s
- **Kubernetes version:** OCP 4.14/4.16 and Kind 1.30
- **Other notable environmental factors:** multi-primary federated on OCP (CRD specifics as mentioned above)

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

Allows you to run multi-cluster Kiali with mixed openshift and kube clusters in `anonymous` mode.

### Steps to test the PR

1. Deploy Kiali on an openshift cluster
    ```
    hack/crc-openshift.sh start                                                                                                                                                          
    oc login -u kubeadmin -p kiali https://api.crc.testing:6443 --insecure-skip-tls-verify                                                                                                                                                                                                  
    podman login --tls-verify=false -u kiali -p (oc whoami -t) default-route-openshift-image-registry.apps-crc.testing                                                                                                                                                                      
    hack/istio/install-istio-via-istioctl.sh -iee true -cp openshift                                                                                                                                                                                                    
    make CLUSTER_TYPE=openshift AUTH_STRATEGY=anonymous build build-ui cluster-push operator-create kiali-create
    hack/istio/install-testing-demos.sh
    ```
2. Create a second cluster with istio installed

    ```
    kind create cluster
    hack/istio/install-istio-via-istioctl.sh -c kubectl -rr true
    hack/istio/install-testing-demos.sh -c kubectl
    ```
3. Create a remote cluster secret for the second cluster

    ```
    hack/istio/multicluster/kiali-prepare-remote-cluster.sh --remote-cluster-context kind-kind --kiali-cluster-context crc-admin --allow-skip-tls-verify true --remote-cluster-url https://$(kubectl get nodes kind-control-plane --context kind-kind -o jsonpath='{.status.addresses[?(@.type == "InternalIP")].address}'):6443
    ```

4. Poke the Kiali operator to get it to reconcile the Kiali CR. Otherwise the Kiali operator won't mount the remote cluster secrets into the server pod.
    ```
    kubectl patch kialis kiali -n kiali-operator --type=json -p '[{"op":"add","path":"/metadata/annotations/reconcile","value":"now"}]'
    ```

5. Open Kiali and verify that there are no errors

### Automation testing

N/A

### Issue reference

Fixes #7665

### CODE REVIEW

**Comment by jmazzitelli** [comment]
In your test procedure, you create your own Kiali CR - what's different in that CR as compared to [the one created](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr_dev.yaml) when you do "make [kiali-create](https://github.com/kiali/kiali/blob/v1.89.1/make/Makefile.operator.mk#L114-L131)" ?

If I read it right, I think its just auth strategy, but you just need to call the `kiali-create` target at the end with the env var set for that:

`make -e CLUSTER_TYPE=openshift AUTH_STRATEGY=anonymous build build-ui cluster-push operator-create kiali-create`

**Comment by nrfox** [comment]
> In your test procedure, you create your own Kiali CR - what's different in that CR as compared to [the one created](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr_dev.yaml) when you do "make [kiali-create](https://github.com/kiali/kiali/blob/v1.89.1/make/Makefile.operator.mk#L114-L131)" ?

I think I had some other changes in here that I deleted. For testing this PR it'd be easier to just use `kiali-create`.

File: business/namespaces.go [hunk 1]
```diff
@@ -67,6 +64,10 @@ func NewNamespaceService(
 	}
 }
 
+func (in *NamespaceService) clusterIsOpenshift(cluster string) bool {
```
Comment (jmazzitelli) [inline business/namespaces.go:67]: just a bug-a-boo of mine.. OpenShift is always with a capital "S".

**Review by jmazzitelli — DISMISSED** [review]
I can't run this - my machine doesn't appear to have enough oomph...

```
$ oc get pods -n gamma
NAME                        READY   STATUS    RESTARTS   AGE
a-client-c888c6c7f-f6rnw    0/2     Pending   0          44m
b-client-98cbcccd7-p499c    0/2     Pending   0          44m
c-client-6998c76bbf-gn5bp   0/2     Pending   0          44m
d-client-5d4f6696fd-ddtqr   0/2     Pending   0          44m
e-client-7676f9bbb4-6lx86   0/2     Pending   0          44m
f-client-55f788cb78-xpm7m   0/2     Pending   0          44m
v-server-5dd44cd4fd-7w22g   0/2     Pending   0          44m
w-server-7f57cb8bf8-kvwtq   0/2     Pending   0          44m
x-server-6b47995bf8-7q2kq   0/2     Pending   0          44m
y-server-6655fddd67-8gcj7   0/2     Pending   0          44m
z-server-6c59bc8f64-6tpst   0/2     Pending   0          44m

$ oc get pods -n gamma -ojsonpath='{..status}'
{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2024-09-09T16:12:03Z","message":"0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.","reason":"Unschedulable",
...
```

But the code looks good and unit tests pass on my machine.

**Comment by nrfox** [comment]
@jmazzitelli you can try omitting this step: `hack/istio/install-testing-demos.sh`. All we're really testing is that the UI doesn't throw errors when you have mixed clusters. Without this change, you'll see errors.

**Comment by jmazzitelli** [comment]
Step 4 you need to get back to the CRC cluster (we are currently in the kind cluster). So step 4 needs to re-log into the CRC cluster first.

`oc login -u kubeadmin -p kiali https://api.crc.testing:6443 --insecure-skip-tls-verify`

**Review by jmazzitelli — APPROVED** [review]
LGTM
image

**Comment by jshaughn** [comment]
@nrfox Nice change, do we need some additional kiali.io doco to go with?
