### PR TITLE
Handle Security appender Ambient corner case

### LINKED ISSUE #7811: kiali doesn't show connection from ambient to sidecar injected namespace as mTLS
### Describe the bug

the scenario is as follows:

- two fresh namespaces - no peer authentication object defined, no network policy defined
- namespace A labeled with istio.io/dataplane-mode=ambient
- namespace B labeled with istio-injection=enabled
- sleep pod with curl installed in namespace A
- ratings pod installed in namespace B
- curl issued from sleep pod in namespace A to ratings pod in namespace B
- response returned, ztunnel logs show the connection as mTLS
- traffic graph in kiali does not show the connection as mTLS
- the same scenario has been tested in different settings: ambient -> sidecar, sidecar -> ambient, ambient -> ambient, sidecar -> sidecar. the only setting where kiali doesn't show the connection as mTLS is in an ambient -> sidecar situation.

curl command:
image

ztunnel logs:
image

traffic graph in kiali:
image

image

### Expected Behavior

assuming the ztunnel logs confirm the connection is mTLS, the traffic graph in kiali should show the same.

### What are the steps to reproduce this bug?

follow along with the scenario above to reproduce.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:** 1.89.7
- **Istio version:** 1.23.1
- **Kubernetes impl:** gardener
- **Kubernetes version:** 1.30.5
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes #7811 

Handle Security appender Ambient corner case. For ztunnel-to-sidecar traffic, we get source reporting only.  Historically we always use destination reporting to determine mtls.
- add necessary queries to security_appender
  - unfortunate but I don't see an alternative
- make sure we disable ambient traffic when ambient is not enabled
  - this saves unnecessary queries
- update unit test 

Test:
@josunect , you already have the environment because you were the one to figure out the problem :-)  I think I updated the queries as you suggested, to look for ztunnel source telem when needed.  Let me know if this solves the issue for you, and if the solution looks good.  It does add queries, and those queries may often return duplicate reporting (because ztunnel typically reports both source and dest telem when source and dest are both in the ambient mesh). Despite adding queries and pulling more date, any duplicates should basically overwrite the original with the same result.

### CODE REVIEW

File: frontend/src/config/ServerConfig.ts [hunk 1]
```diff
@@ -169,6 +169,9 @@ export const setServerConfig = (cfg: ServerConfig): void => {
 
   homeCluster = getHomeCluster(serverConfig);
   isMultiCluster = isMC();
+  if (!serverConfig.ambientEnabled) {
+    serverConfig.kialiFeatureFlags.uiDefaults.graph.traffic.ambient = 'none';
```
Comment (josunect) [inline frontend/src/config/ServerConfig.ts:173]: Is this used somewhere else?

File: graph/telemetry/istio/appender/security_policy.go [hunk 2]
```diff
@@ -195,6 +195,35 @@ func (a SecurityPolicyAppender) appendGraph(trafficMap graph.TrafficMap, namespa
 			query = fmt.Sprintf(`%s OR (%s)`, query, tcpReceivedQuery)
 		}
 	}
+	// If we are including ztunnel traffic we may need more TCP queries, because for ztunnel-to-sidecar traffic ztunnel
+	// will report as source telemetry. If this results in duplicate source and dest ztunnel telem, it should be OK, as
+	// the rate should be the same, and will just overwrite itself.
+	if a.Rates.Ambient == graph.AmbientTrafficTotal || a.Rates.Ambient == graph.AmbientTrafficZtunnel {
```
Comment (josunect) [inline graph/telemetry/istio/appender/security_policy.go:201]: I've though it would be useful for this waypoint code: https://github.com/kiali/kiali/pull/7756/files#diff-55173479d7c6bec43bb8b3b60d6b5d67bd408e9d3b8c70ea176c6b75e4eff0cfR317 
But it looks like it is not applicable here.

File: frontend/src/config/ServerConfig.ts (hunk 1 above)
Comment (jshaughn) [reply frontend/src/config/ServerConfig.ts:173]: The value ends up being used when we are setting the traffic options for graph generation requests.  Without this change we will, by default, ask the graph-gen code to include ambient traffic, even if the ambient profile in not enabled.

I considered changing this server-side but decided that it was better to return the real server config from the server, and let clients modify it as they see fit.  We also do some massaging of the health config, so updating the server config does have a precedent.

File: graph/telemetry/istio/appender/security_policy.go (hunk 2 above)
Comment (jshaughn) [reply graph/telemetry/istio/appender/security_policy.go:201]: I don't think so, but I do think we will see more corner cases. We always want to minimize the number of queries, so we have to be careful about what we add. One thing to notice in this appender is that we actually minimize the number of prometheus round trips, because we use OR expressions.  This is sort of a trick, but works as long as each sub-query has the same `by (...)` clause.  When that is true you can actually query different metrics all within the same prom query.
