### PR TITLE
Multicluster services list page

### LINKED ISSUE #5943: Multicluster - Services view
Services list page shows services from multiple clusters. Some work on the detail page may need to be included so that links are not broken but getting everything to work on the details page will be a separate issue.

#5919

### LINKED ISSUE #5960: Multi-cluster list view - Services
Workloads list page pulls workloads from all configured clusters.

### PR DESCRIPTION
**Pull request by nrfox**
Implements multi cluster services list.

Fixes #5960

### CODE REVIEW

File: kubernetes/cache/namespaces.go
Comment (nrfox) [inline kubernetes/cache/namespaces.go:1]: I updated this to include `cluster` in the key because without this the cache could return a namespace for a different cluster and most callers of the cache are just checking if `ns != nil`. See [this test](https://github.com/kiali/kiali/pull/5998/files#diff-b4f5651eca4cec992ad548c9625937d5cc407a526449db05e3ac0f6184a57db2R237-R268) for more details.

**Comment by hhovsepy** [comment]
The code looks good to me, have run locally:
Screenshot from 2023-04-06 11-12-58

**Comment by hhovsepy** [comment]
Regression tested on single OCP cluster.

File: prometheus/metrics.go [hunk 1]
```diff
@@ -144,8 +144,8 @@ func getNamespaceServicesRequestRates(ctx context.Context, api prom_v1.API, name
 // getServiceRequestRates retrieves traffic rates for requests entering, or internal to the namespace, for a specific service name
 // Note that it does not discriminate on "reporter", so rates can be inflated due to duplication, and therefore
 // should be used mainly for calculating ratios (e.g total rates / error rates)
-func getServiceRequestRates(ctx context.Context, api prom_v1.API, namespace, service string, queryTime time.Time, ratesInterval string) (model.Vector, error) {
-	lbl := fmt.Sprintf(`destination_service_name="%s",destination_service_namespace="%s"`, service, namespace)
+func getServiceRequestRates(ctx context.Context, api prom_v1.API, cluster, namespace, service string, queryTime time.Time, ratesInterval string) (model.Vector, error) {
+	lbl := fmt.Sprintf(`destination_service_name="%s",destination_service_namespace="%s",destination_cluster="%s"`, service, namespace, cluster)
```
Comment (leandroberetta) [inline prometheus/metrics.go:148]: Do we want just traffic from the cluster that the service lives in, or from any cluster the traffic comes from?.

File: business/services.go [hunk 2]
```diff
@@ -48,24 +49,70 @@ func (in *SvcService) GetServiceList(ctx context.Context, criteria ServiceCriter
...
-	var pods []core_v1.Pod
-	var deployments []apps_v1.Deployment
-	var istioConfigList models.IstioConfigList
-	var err error
-
+	serviceList := models.ServiceList{}
 	// Check if user has access to the namespace (RBAC) in cache scenarios and/or
 	// if namespace is accessible from Kiali (Deployment.AccessibleNamespaces)
-	if _, err = in.businessLayer.Namespace.GetNamespace(ctx, criteria.Namespace); err != nil {
+	for cluster := range in.userClients {
```
Comment (leandroberetta) [inline business/services.go:55]: Performance wise, can we implement this fetches with go routines?.

**Review by leandroberetta — COMMENTED** [review]
Code looks good, I have only two comments below.

File: prometheus/metrics.go (hunk 1 above)
Comment (leandroberetta) [reply prometheus/metrics.go:148]: I think you're right. We are interested in the traffic rates from any service/cluster to the destination service, which lives in a cluster.

**Comment by nrfox** [comment]
Putting "do no merge" label until #6007 is fixed since that will affect this PR too.

**Review by josunect — COMMENTED** [review]
Service list with multicluster: 

image

image

But shouldn't the configuration be applicable for the local cluster? This is an example (from master branch) 

image

**Comment by nrfox** [comment]
> But shouldn't the configuration be applicable for the local cluster? This is an example (from master branch)

You're right! I forgot to add the validations to the response. Good catch.

**Comment by hhovsepy** [comment]
Tested locally:
Screenshot from 2023-04-13 20-34-09

**Comment by hhovsepy** [comment]
The missing '?cluster' params in service detils references could be added in a further PRs.

**Review by hhovsepy — APPROVED** [review]
