### PR TITLE
[CI] Validate tracing reporting

### LINKED ISSUE #9608: [CI] Detect the way that Waypoints are generating tracing
### Describe the bug

- Waypoint traces are generated using the service name (from Istio 1.29).
- Before that, traces were created using the waypoint as the service names
- Installing the Istio new version with Sail, even if tracing is installed with an oTEL collector, the traces are created using the waypoint name: https://github.com/kiali/kiali/actions/runs/24951496790/job/73062704103

Image

Image

Image

Image

The CI should detect with queries to tracing the way traces are created, and update the Kiali CR if required.

### What are the steps to reproduce this bug?

1. …
2. …
3. …

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change
- Detect the way that Waypoints are generating tracing and change the Kiali CR use_waypoint_proxy if no traces found. This should fix the Istio versions worklows.
- Add a workaround in select span workload to lookup for 'waypoint' when the workload information is not available in the span. 

### Steps to test the PR

- Tested Sail main: https://github.com/josunect/kiali/actions/runs/25102027980/job/73555011588
- Tested 1.28.3: https://github.com/josunect/kiali/actions/runs/25103066430/job/73558583568 
- Tested nightly Ambient (Passed)

### Automation testing

If applicable, explain the case scencarios covered by **unit / integration / e2e** tests created for this PR.

### Issue reference

Fixes https://github.com/kiali/kiali/issues/9608

### CODE REVIEW

File: frontend/cypress/integration/common/navigation.ts [hunk 1]
```diff
@@ -209,16 +209,15 @@ export const clusterParameterExists = (present: boolean): void => {
...
-    const expectedSelector = `li[label="${expectedOption}"]`;
-    if ($body.find(expectedSelector).length > 0) {
-      cy.get(expectedSelector).should('be.visible').find('button').click();
-      return;
-    }
-
-    const fallbackSelector = `li[label="${fallbackOption}"]`;
-    cy.get(fallbackSelector).should('be.visible').find('button').click();
-  });
+  cy.get('ul[role="listbox"]')
```
Comment (hhovsepy) [inline frontend/cypress/integration/common/navigation.ts:212]: It seems this code block is a code duplicate with different params, it can be made as a separate function and be called in all places.

**Comment by hhovsepy** [comment]
Hi @josunect , lgtm, just one small comment of a code reuse, meanwhile I will regression run Ambient tests on OCP cluster via Jenkins job.

**Comment by hhovsepy** [comment]
Jenkins job finished fine.

File: frontend/cypress/integration/common/navigation.ts (hunk 1 above)
Comment (josunect) [reply frontend/cypress/integration/common/navigation.ts:212]: Good point, @hhovsepy ! Updated

**Review by hhovsepy — APPROVED** [review]
lgtm, thanks @josunect

**Comment by josunect** [comment]
Thanks for the review! 
Run again Test Istio version: https://github.com/josunect/kiali/actions/runs/25163443048/job/73771849897 passed
