### PR TITLE
[overview] Improve handling when istio API is disabled

### LINKED ISSUE #9299: [Overview page] Review istio_api_enabled to false
### Describe the bug

When the config `istio_api_enabled` is set to false, there are many cache misses in the logs: 

```
2026-03-03T12:02:39Z DBG health cache miss for cluster=Kubernetes namespace=travel-control type=app, returning unknown status
2026-03-03T12:02:39Z DBG health cache miss for cluster=Kubernetes namespace=travel-control type=service, returning unknown status
2026-03-03T12:02:39Z DBG health cache miss for cluster=Kubernetes namespace=travel-control type=workload, returning unknown status
2026-03-03T12:02:39Z DBG health cache miss for cluster=Kubernetes namespace=travel-portal type=app, returning unknown status
2026-03-03T12:02:39Z DBG health cache miss for cluster=Kubernetes namespace=travel-portal type=service, returning unknown status
```

And the Overview page is not looking good: 

Image

After some minutes, the cache is populated and the Applications and service insights works well. But still, there are no visible clusters: 

Image

The difference with status with istio_api_enabled: true

Image

Another missing feature was, that when the istio API was disabled, there was a badge in the control plane card: 

Image

That indicates the user that some functions will work differently. 

### What are the steps to reproduce this bug?

Set:
```

external_services:
  istio:
    istio_api_enabled: false
```

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes #9299 

This PR does several things to improve handling when the Istio API is disabled. Several changes affect the new Overview page, but some also affect other parts of the code:

- Don't skip the initial mesh discovery because we need to establish a list of clusters.
  - This affects the health cache initialization and potentially other things as well.
  - It was causing 0 clusters to be reported in overview and messing up  health status
- Ensure we establish a component status for each cluster.
- Ensure control planes card status aligns with the status of the control plane namespace(s).
  - This was confusing because originally the status' may not align
- Add a badge to the overview control plane card when istio api is disabled
  - add a new badge component so this can be consistently used in multiple places
- Because validation no longer requires the Istio API:
  - Remove a bunch of server and ui-side guards
  - We were unnecessarily blocking, or warning about the lack of, configuration validation

### CODE REVIEW

**Comment by jshaughn** [comment]
@Joeyyubo This PR has an item for UX review. The PR has to do with resolving issues on the new Overview page when the installation has disabled the Istio API. When that happens Kiali can not access some of the information it typically uses, and it can affect our ability to determine things like control plane status.

In the previous Overview page we had an additional badge on control plane cards when the API was disabled:
image

I was talking with @josunect and we thought maybe we could add that badge back into the control planes card on the new page. I have done that, but wanted your opinion on it:
image

File: business/istio_status.go [hunk 1]
```diff
@@ -58,10 +58,47 @@ func (iss *IstioStatusService) GetStatus(ctx context.Context) (kubernetes.IstioC
 	)
 	defer end()
 
-	if !iss.conf.ExternalServices.Istio.ComponentStatuses.Enabled || !iss.conf.ExternalServices.Istio.IstioAPIEnabled {
+	if !iss.conf.ExternalServices.Istio.ComponentStatuses.Enabled {
 		return kubernetes.IstioComponentStatus{}, nil
 	}
 
+	// When Istio API is disabled we cannot query istiod for component health, but we still
```
Comment (josunect) [inline business/istio_status.go:70]: I wonder if Istiod is not accessible, we might still be checking other components as Prometheus? 
Shouldn't be more accurate to return some other status like `n/a` or `unknown`?

File: frontend/src/components/Badge/IstioAPIDisabledBadge.tsx [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+export const IstioAPIDisabledBadge: React.FC<{ style?: React.CSSProperties }> = ({ style }) => {
+  const istioAPIEnabled = useSelector((state: KialiAppState) => state.statusState.istioEnvironment.istioAPIEnabled);
+
+  if (istioAPIEnabled) {
+    return null;
+  }
+
+  return (
+    <Label style={{ marginLeft: '0.5rem', ...style }} color="orange" isCompact data-test="istio-api-disabled-badge">
+      Istio API disabled
```
Comment (josunect) [inline frontend/src/components/Badge/IstioAPIDisabledBadge.tsx]:
```suggestion
      {t('Istio API disabled')}
```

File: frontend/src/pages/Overview/ControlPlaneStats.tsx [hunk 3]
```diff
@@ -90,6 +91,7 @@ export const ControlPlaneStats: React.FC = () => {
                 </div>
               </Popover>
             )}
+            <IstioAPIDisabledBadge />
```
Comment (josunect) [inline frontend/src/pages/Overview/ControlPlaneStats.tsx:94]: I was thinking if this is common to all the control planes, I guess it is. Otherwise another place could be the namespace page? 

Image

Comment (jshaughn) [reply frontend/src/pages/Overview/ControlPlaneStats.tsx:94]: Oh, I didn't see that occurrence. I'll update it.

**Comment by Joeyyubo** [comment]
One question for context:
 if the installation disables the Istio API, will it affect all control planes?

File: business/istio_status.go (hunk 1 above)
Comment (jshaughn) [reply business/istio_status.go:70]: `n/a` is probably the most accurate. But I think the best thing here, if it's possible, would be to match the control plane namespace health. It was a mismatch between the namespace health and the overview card that I found so confusing. I'll see if that's possible.

**Comment by jshaughn** [comment]
> if the installation disables the Istio API, will it affect all control planes?

Yes, we have only one setting in the config, not a setting per control plane.

File: frontend/src/pages/Overview/ControlPlaneStats.tsx (hunk 3 above)
Comment (jshaughn) [reply frontend/src/pages/Overview/ControlPlaneStats.tsx:94]: Ah, I didn't read your comment carefully. You are asking whether this is common to all control planes. I think the answer is yes, we only have the one `external_services.istio.istio_api_enabled` config setting. So, I don't think we need to add more badging in the list itself.

File: business/istio_status.go (hunk 1 above)
Comment (jshaughn) [reply business/istio_status.go:70]: OK, I pushed the change for this. It was not trivial but should improve the alignment between the control plane card's health status and the control plane namespace health on the Namespaces page.

**Comment by Joeyyubo** [comment]
Thanks for the update @jshaughn @josunect . 
I’ve reviewed the current screenshots. From a UX and functional perspective, I have several concerns and suggestions regarding how we communicate this to the user:

**1.** Currently, Namespace Health is an aggregate of Apps + Services + Workloads. If the Istio API is disabled, Kiali sees the istiod pod is Running via the K8s API and might mark the Control Plane as "Healthy". However, this is a "False Health" because we have zero visibility into Istio-level metrics (telemetry, sync status, etc.).
UX Recommendation: We should distinguish between health Status (Is the process running?) and Telemetry Status (Can we see the data?). I suggest using a neutral status like "Unknown" or "Limited Data" to override the aggregate status when the API is disabled. Showing a green "Healthy" checkmark when data is missing is misleading.

**2.** The current namespace page adds the "Istio API disabled" label to the type label.Since the ‘Istio API disabled’is a global setting, adding this label to 20 or 50 individual rows creates significant visual clutter and redundancy.
UX Recommendation: Could we use a Namespace-level indicator or a single Global Banner/Notification at the top of the page? This would clean up the table while still informing the user of the restriction.

3. Following the logic above, If the Istio API is disabled, does the "Health" column for namespaces still provide value? If we can't verify the internal state of a namespace, a generic "Healthy" status might actually decrease user trust in Kiali's diagnostics.

4.some questions: 
- Is "Istio API disabled" typically an intentional security choice or a configuration error?  
- Is there clear documentation in Istio or Kiali explaining the "Istio API Disabled" circumstance? 
- if disabling the Istio API affects the Health Status of the Data Plane?

**Comment by josunect** [comment]
> Thanks for the update @jshaughn @josunect . I’ve reviewed the current screenshots. From a UX and functional perspective, I have several concerns and suggestions regarding how we communicate this to the user:
> 
> **1.** Currently, Namespace Health is an aggregate of Apps + Services + Workloads. If the Istio API is disabled, Kiali sees the istiod pod is Running via the K8s API and might mark the Control Plane as "Healthy". However, this is a "False Health" because we have zero visibility into Istio-level metrics (telemetry, sync status, etc.). UX Recommendation: We should distinguish between health Status (Is the process running?) and Telemetry Status (Can we see the data?). I suggest using a neutral status like "Unknown" or "Limited Data" to override the aggregate status when the API is disabled. Showing a green "Healthy" checkmark when data is missing is misleading.
> 
> **2.** The current namespace page adds the "Istio API disabled" label to the type label.Since the ‘Istio API disabled’is a global setting, adding this label to 20 or 50 individual rows creates significant visual clutter and redundancy. UX Recommendation: Could we use a Namespace-level indicator or a single Global Banner/Notification at the top of the page? This would clean up the table while still informing the user of the restriction.
> 
>     3. Following the logic above, If the Istio API is disabled, does the "Health" column for namespaces still provide value? If we can't verify the internal state of a namespace, a generic "Healthy" status might actually decrease user trust in Kiali's diagnostics.
> 
> 
> 4.some questions:
> 
>     * Is "Istio API disabled" typically an intentional security choice or a configuration error?
That can be a security implication due to restrictions in the network, I think it usually would be intentional. 
> 
>     * Is there clear documentation in Istio or Kiali explaining the "Istio API Disabled" circumstance?
You can find some information here: https://kiali.io/docs/configuration/no-istiod/ 
> 
>     * if disabling the Istio API affects the Health Status of the Data Plane?
It should no be a problem calculate the health status of the data plane with istio api disabled

**Comment by jshaughn** [comment]
Hi @Joeyyubo, @josunect, thanks for the feedback, my comments:

> 1. Currently, Namespace Health is an aggregate of Apps + Services + Workloads. If the Istio API is disabled, Kiali sees the istiod pod is Running via the K8s API and might mark the Control Plane as "Healthy". However, this is a "False Health" because we have zero visibility into Istio-level metrics (telemetry, sync status, etc.). UX Recommendation: We should distinguish between health Status (Is the process running?) and Telemetry Status (Can we see the data?). I suggest using a neutral status like "Unknown" or "Limited Data" to override the aggregate status when the API is disabled. Showing a green "Healthy" checkmark when data is missing is misleading.

You both indicated that showing `Healthy` was a mistake in the initial PR impl. I agree and I have made a change that I think is good. With the API disabled, the health status should now match the status of the control plane namespace (as opposed to the istiod component). This should be a consistent experience for the user, because the `control planes` link will bring you to the namespaces list.

I don't think "Unknown" is good, because it's not totally unknown, the namespace health status will be a good indicator.

> 2. The current namespace page adds the "Istio API disabled" label to the type label.Since the ‘Istio API disabled’is a global setting, adding this label to 20 or 50 individual rows creates significant visual clutter and redundancy. UX Recommendation: Could we use a Namespace-level indicator or a single Global Banner/Notification at the top of the page? This would clean up the table while still informing the user of the restriction.

Actually, the Namespaces table does not have that badge. The screenshot from Josune was just a "mock" idea. I don't think we need to indicate "Istio API Disabled" on the Namespaces, namespaces health can be calculated independently (as a combination of service, app and workload health data).

If we want to ensure that users always know that the Istio API is disabled, we could possibly badge the masthead, but that seems like possible overkill.  I added the badge in the Control Planes card in this PR, so maybe that is sufficient?

> 3. Following the logic above, If the Istio API is disabled, does the "Health" column for namespaces still provide value? If we can't verify the internal state of a namespace, a generic "Healthy" status might actually decrease user trust in Kiali's diagnostics.

Yes, for the reason above, Namespace health can be determined without the API.

> 4.some questions:

I agree with all of Josune's responses.

So, to summarize, I think the latest revision of the PR is sufficient when the Istio API is disabled. We have resolved several issues, and as of the last commit the control plane status aligns with the control plane namespace(s) status. I think we are OK for a final review. As always, we can iterate going forward.
