### PR TITLE
[UI] fix bug in health status tooltip content where pod status was unset

### LINKED ISSUE #9471: [UI] workload list health status tooltip always showing 0 pods
On the workload list page the health status tooltip is not showing proper pod status:

Image

Image

Navigating to workload detail shows this is untrue, even in the failure case:

Image

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes #9471 

Fix bug in health status tooltip content where pod status was unset
  - this affected a few different places
  - make sure we're using a consistent duration (i.e rateInterval) in UI and server for health status calc.
- improve the "health config" part of the tooltip to make it more understandable
  - even I could not parse what it was trying to say
  - also, fixed a bug in the config parsing

**Before (broken and old config range info):**

image

image

**After (working and explicit config range info):**

image

image

### CODE REVIEW

File: frontend/src/pages/WorkloadList/WorkloadListPage.tsx [hunk 1]
```diff
@@ -145,7 +145,11 @@ class WorkloadListPageComponent extends FilterComponent.Component<
         isWaypoint: deployment.isWaypoint,
         isZtunnel: deployment.isZtunnel,
         additionalDetailSample: deployment.additionalDetailSample,
-        health: WorkloadHealth.fromBackendStatus(deployment.health),
+        health: WorkloadHealth.fromJson(deployment.namespace, deployment.name, deployment.health ?? {}, {
```
Comment (jmazzitelli) [inline frontend/src/pages/WorkloadList/WorkloadListPage.tsx:148]: Pre-existing client/server mismatch worth noting: switching from `fromBackendStatus` to `fromJson` means list pages now run the full client-side health computation (`computeItems` → `calculateErrorRate` → `ascendingThresholdCheck`). This is correct and fixes the tooltip bug, but it also exposes a pre-existing discrepancy when a tolerance config has `failure === 0`.

**Server** (`business/health_calculator.go:223`): `if failure > 0 && errorRatio >= failure` — skips the failure tier entirely when `failure=0`.

**Client** (`frontend/src/types/Health.ts:312`): `if (value >= thresholds.failure)` — when `failure=0` and `value > 0`, this is always true, so any positive error rate is classified as Failure.

The health badge uses the backend status (`getStatus()` → `backendStatus`), while the tooltip detail text uses the client-computed status from `computeItems`. With `failure=0` and any errors, the badge could show Degraded while the tooltip says Failure.

Not a blocker for this PR since it's pre-existing (detail pages already have this path), but worth tracking as a follow-up.

Comment (jshaughn) [reply frontend/src/pages/WorkloadList/WorkloadListPage.tsx:148]: Well, better now than never. It's a small change so may as well add it. I pushed the change.
