### PR TITLE
Promote Istio API to v1

### LINKED ISSUE #7398: Kiali 1.85.0 - Istio 1.22 : display istio resources V1 as V1Beta1
### Describe the bug

With Istio 1.22.0 a lot of resources as VS, DR, SE have been released in version V1. If we install the Kiali as addons with the helm chart in version 1.85.0, the istio resources are displayed in the Kiali UI with the version V1Beta1.
If we get the istio resources with the kubectl get vs, dr, se -A the version of all resources are V1.

### Expected Behavior
The version of the Istio resources displayed in the Kiali UI should be V1 and not V1Beta1

### What are the steps to reproduce this bug?

1. Install Istio in version 1.22.0
2. Install Kiali with the helm chart in version 1.85.0
3. Deploy a SE as below in your cluster:
```yaml
kind: ServiceEntry
apiVersion: networking.istio.io/v1
metadata:
  name: keycloak
  namespace: my-ns
spec:
  hosts:
    - identity.my-ns.xxxxxxx
  ports:
    - number: 443
      protocol: HTTPS
      name: https
  resolution: DNS
  exportTo:
    - .
```
4. If you get the resource with kubectl get service-entry keycloak -n my-ns -oyaml
You see the good version V1 for the resources.
5. In the Kiali, in the Istio Config tab, if you select the same resource, the version displayed to the top will be v1beta1
image

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 1.85.0 **
- **Istio version: 1.22.0 **
- **Kubernetes impl: EKS** 
- **Kubernetes version: 1.29**

### PR DESCRIPTION
**Pull request by ferhoyos**
### Describe the change

With Istio 1.22.0 a lot of resources as VS, DR, SE have been released in version V1 (https://medium.com/google-cloud/everything-new-with-istio-1-22-9cded0ccd759). This PR promotes networking, security and telemetry Istio API to v1 in Kiali application.

**Bonus**: Kiali internal API `kiali_internal_api.md` file has been re-generated to update API version

### Steps to test the PR

1. Try to create any Virtual Service, Destination Rule or Service Entry in Kiali
2. Verify that apiVersion is `networking.istio.io/v1`

image

3. The same applies for AuthorizationPolicy

image

### Automation testing

N/A

### Issue reference

Closes #7398

### CODE REVIEW

File: kubernetes/types.go [hunk 1]
```diff
@@ -113,6 +113,18 @@ var (
 	}
 	ApiNetworkingVersionV1Alpha3 = NetworkingGroupVersionV1Alpha3.Group + "/" + NetworkingGroupVersionV1Alpha3.Version
 
+	NetworkingGroupVersionV1Beta1 = schema.GroupVersion{
+		Group:   "networking.istio.io",
+		Version: "v1beta1",
+	}
+	ApiNetworkingVersionV1Beta1 = NetworkingGroupVersionV1Beta1.Group + "/" + NetworkingGroupVersionV1Beta1.Version
```
Comment (nrfox) [inline kubernetes/types.go:120]: Do the older versions need to stay here?

File: tests/data/references/multiple-gateways.yaml [hunk 2]
```diff
@@ -1,60 +1,60 @@
...
   name: reviews-well
   namespace: bookinfo
 spec:
   hosts:
-    - 'reviews.prod.svc.cluster.local'
+  - 'reviews.prod.svc.cluster.local'
   gateways:
-    - gateway1
-    - bookinfo2/gateway2
-    - mesh
```
Comment (nrfox) [inline tests/data/references/multiple-gateways.yaml:12]: Some yaml linter?

**Review by nrfox — COMMENTED** [review]
One question but otherwise LGTM. You'll also need to update the compat matrix on kiali.io since after this gets merged the next release will no longer be compatible with versions of istio < 1.22.

**Comment by aljesusg** [comment]
Care with this. 
We don't know if we are going to have a 2.6.

Ar this moment 2.6 will ship istio 1.20 so if we merge this will have an old kiali version and not the latest one for 2.6

I'll wait to discuss this

**Comment by ferhoyos** [comment]
Agree with you, @aljesusg. We need to ensure that this change does not break our plans for OSSM.

As you mentioned, theoretically, there should be no problem since OSSM 2.6 will use kiali 1.73, and OSSM 3.0 will have Istio 1.22.

In any case, I will wait to discuss this with the rest of the team before merging this PR.

File: tests/data/references/multiple-gateways.yaml (hunk 2 above)
Comment (ferhoyos) [reply tests/data/references/multiple-gateways.yaml:12]: Yes, we added yaml linter some time ago (https://github.com/kiali/kiali/pull/7011) to ensure consistency across Kiali application.

File: kubernetes/types.go (hunk 1 above)
Comment (ferhoyos) [reply kubernetes/types.go:120]: It is used in `kubernetes/filters.go`:

```
func FilterSupportedGateways(gateways []*networking_v1.Gateway) []*networking_v1.Gateway {
	filtered := []*networking_v1.Gateway{}
	for _, gw := range gateways {
		if gw.APIVersion == ApiNetworkingVersionV1 || gw.APIVersion == ApiNetworkingVersionV1Beta1 || gw.APIVersion == ApiNetworkingVersionV1Alpha3 {
			filtered = append(filtered, gw)
		}
	}
	return filtered
}
```
Actually I don't know why we are checking the apiVersion of the gateway. Do you think we could directly remove that if statement?
```
for _, gw := range gateways {
	filtered = append(filtered, gw)
}
```

Comment (hhovsepy) [reply kubernetes/types.go:120]: It seems `FilterSupportedGateways` is not used anymore, so it can be removed. 
Another place where `NetworkingGroupVersionV1Beta1` is used is https://github.com/kiali/kiali/blob/master/business/istio_config.go#L978 but it needs to be edited to `NetworkingGroupVersionV1`.
And you can remove 'NetworkingGroupVersionV1Beta1'.

**Comment by hhovsepy** [comment]
Tested locally and on OCP cluster, works fine.

File: kubernetes/types.go (hunk 1 above)
Comment (ferhoyos) [reply kubernetes/types.go]: Thanks @hhovsepy, I have removed `NetworkingGroupVersionV1Beta1` with your comments.

File: kubernetes/types.go [hunk 3]
```diff
@@ -131,12 +137,6 @@ var (
...
 
-	NetworkingGroupVersionV1Beta1 = schema.GroupVersion{
-		Group:   "networking.istio.io",
-		Version: "v1beta1",
-	}
-	ApiNetworkingVersionV1Beta1 = NetworkingGroupVersionV1Beta1.Group + "/" + NetworkingGroupVersionV1Beta1.Version
-
 	SecurityGroupVersion = schema.GroupVersion{
 		Group:   "security.istio.io",
 		Version: "v1beta1",
```
Comment (hhovsepy) [inline kubernetes/types.go:142]: Shouldn't this be 'v1'?

Comment (hhovsepy) [inline kubernetes/types.go:142]:
```suggestion
		Version: "v1",
```

File: kubernetes/types.go [hunk 4]
```diff
@@ -149,11 +149,11 @@ var (
 	}
 	ApiExtensionV1Alpha1 = ExtensionGroupVersionV1Alpha1.Group + "/" + ExtensionGroupVersionV1Alpha1.Version
 
-	TelemetryGroupV1Alpha1 = schema.GroupVersion{
+	TelemetryGroupV1 = schema.GroupVersion{
 		Group:   "telemetry.istio.io",
 		Version: "v1alpha1",
```
Comment (hhovsepy) [inline kubernetes/types.go:154]:
```suggestion
		Version: "v1",
```

Comment (hhovsepy) [reply kubernetes/types.go:154]: same here. to be 'v1'

**Comment by hhovsepy** [comment]
Hi @ferhoyos , have suggested 2 changes, otherwise lgtm.

File: doc.go [hunk 5]
```diff
@@ -796,6 +806,34 @@ type MetricsStatsResponse struct {
...
+type ClustersNamespaceHealthResponse struct {
+	// in: body
+	Body models.ClustersNamespaceHealth
+}
+
+// Response of the mesh query
+// swagger:response meshResponse
+type MeshResponse struct {
+	// in: body
+	Body business.Mesh
```
Comment (hhovsepy) [inline doc.go:827]: It seems some doc is auto-generated.

**Review by hhovsepy — APPROVED** [review]
Tested on OCP cluster.
