### PR TITLE
Fix manage_istio_config to work with mcp

### LINKED ISSUE #9521: [AI] manage_istio_config returns UI-only actions payload to MCP clients that cannot handle it
# Description

The manage_istio_config tool (create/patch/delete operations) always returns an actions array containing file-kind actions with YAML previews. This works correctly for the Kiali chatbot UI, which renders file previews and provides an "Apply" button. However, when the tool is called via the MCP endpoint by external agents (e.g., Gemini CLI, Claude, etc.), the actions payload is meaningless — MCP clients have no UI to render file previews or apply YAML from an editor.

## current behavior

For both the chatbot and MCP paths, Execute() returns:

```json
{
  "actions": [{ "kind": "file", "fileName": "vs_reviews.yaml", "payload": "..." }],
  "result": "PREVIEW READY: A YAML preview for the 'create' operation has been prepared..."
}
```
When called from MCP:

The agent receives a file action it cannot interpret
The preview/confirm flow (confirmed: false → show preview → confirmed: true) doesn't work because the MCP agent has no way to render or edit the YAML file attachment
On confirmed execution, the response still wraps the result inside an actions + result struct, which confuses MCP agents expecting a direct result
Expected behavior:

When the request originates from the MCP endpoint:

Preview (confirmed: false): Return the YAML content directly as a string result so the agent can show it to the user in its own interface
Execute (confirmed: true): Return only the operation result without wrapping it in an actions struct
Delete preview: Same as above — return the YAML content directly
The tool should detect whether the request is from the chatbot UI or the MCP endpoint (e.g., via a context flag or the KialiInterface) and adapt the response format accordingly.

Affected paths in manage_istio_config.go:

Execute() lines 99-138 (create/patch with confirmed: false and confirmed: true)
Execute() lines 141-155 (delete with confirmed: false)

### PR DESCRIPTION
**Pull request by aljesusg**
Fix https://github.com/kiali/kiali/issues/9521

### CODE REVIEW

**Review by josunect — APPROVED** [review]
LGTM

File: frontend/src/services/Api.ts [hunk 1]
```diff
@@ -128,7 +128,7 @@ const loginHeaders = config.login.headers;
 const getHeaders = (method: HTTP_VERBS, urlEncoded: boolean): Partial<AxiosHeaders> => {
   if (apiProxy) {
     // apiProxy is used by OSSMC, which doesn't need Kiali login headers (and can cause CORS issues)
-    const headers = { 'Content-Type': 'application/x-www-form-urlencoded' };
+    const headers = { 'Content-Type': 'application/x-www-form-urlencoded', 'Kiali-UI': 'true' };
```
Comment (ferhoyos) [inline frontend/src/services/Api.ts:131]: @aljesusg this part of the code is used only in OSSMC (where apiProxy is defined). I think `Kiali-UI` headers should be included in line 140 and line 142, which belongs to the standalone Kiali application. Or am I missing something?

Comment (aljesusg) [reply frontend/src/services/Api.ts:131]: It should be here too. OSSMC is using API endpoints too. But yes we should add it to the other place too.

Anyway we have a control in the mcp side too with another header.
