### PR TITLE
remove GraphSelectorBuilder

### LINKED ISSUE #8258: Node selection not working when navigating to graph from trace detail
This is a problem since moving to the PFT graph, because the PFT graph only supports focus based on nodeId.  Not sure if we can/should solve the issue or just remove the feature.  If it's too difficult to support a more robust focus selector then we should remove the feature from TraceDetail and the GraphSelector helper class.

I think this regression is not worth solving unless motivated by a user request. As such, I think we should just remove the relevant, broken code.

The workaround is that when you arrive in the graph page, if you can't locate the node use Graph Find.

### PR DESCRIPTION
**Pull request by jshaughn**
This removes GraphSelectorBuilder, which was implemented based on Cytoscape Selector syntax. It allowed non-graph code, like Trace Detail, to navigate to the graph and attempt to focus on the related node (perform the node "flashing"), to help orient the user the relevant node on the graph.

In the PFT graph we only offer node focus based on NodeId. We could have implemented something similar for PFT, using our "home grown selectors", but it was decided (well, mainly by me) that the slight regression didn't merit the effort. I don't think users will notice (note that it hasn't worked since PFT became the default graph), and users always have the option to use Graph-Find to locate the node, if desired.

- also, replaced some 'focusSelector' literals with an existing constant.

closes #8258

To Test: Navigate to a Trace Detail, select 'Show On Graph' from kebab. It should work, and the trace should be in the side panel, but you won't see any flashing on the target node. Note, this is the same as before the PR, it's just that now we won't even try to do the focus node logic.

### CODE REVIEW

File: frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx [hunk 1]
```diff
@@ -88,26 +87,9 @@ class TraceDetailsComponent extends React.Component<Props, State> {
...
-      case 'workload':
-        graphType = GraphType.WORKLOAD;
-        graphSelector = graphSelector.workload(this.props.target);
-        break;
-    }
-
-    return `/graph/namespaces?graphType=${graphType}&injectServiceNodes=true&namespaces=${
-      this.props.namespace
-    }&traceId=${traceID}&focusSelector=${encodeURI(graphSelector.build())}`;
+    return `/graph/namespaces?graphType=${graphType}&injectServiceNodes=true&namespaces=${this.props.namespace}&traceId=${traceID}`;
```
Comment (ferhoyos) [inline frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx:92]: Is `graphType` value always `GraphType.APP`? I think you should maintain the switch statement to determine the `graphType`

Comment (jshaughn) [reply frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx:92]: hmm, I think you are right. I'll change that back.

Comment (jshaughn) [reply frontend/src/components/TracingIntegration/TracingResults/TraceDetails.tsx:101]: fixed, gracias

File: frontend/src/pages/Graph/MiniGraphCard.tsx [hunk 2]
```diff
@@ -371,9 +371,9 @@ class MiniGraphCardComponent extends React.Component<MiniGraphCardProps, MiniGra
     const selected = selectAnd(elems(this.state.graphRefs!.getController()).nodes, [
       { prop: 'isSelected', op: 'truthy' }
     ]);
-    const focusSelector = selected.length > 0 ? `&focusSelector=${encodeURI(selected[0].getId())}` : '';
+    const focusSelector = selected.length > 0 ? `${URLParam.FOCUS_SELECTOR}=${encodeURI(selected[0].getId())}` : '';
```
Comment (ferhoyos) [inline frontend/src/pages/Graph/MiniGraphCard.tsx:374]: I like the idea of replacing hardcode url parameters with the URLParam enum, we should continue this effort in follow-up PRs (for example with `injectServiceNodes` and `namespaces` params in the the graphUrl below)

**Review by ferhoyos — APPROVED** [review]
Good cleanup @jshaughn! This one was hard to figure out that only applies to Cytoscape.
