### PR TITLE
[Overview] Hide View Mesh if the user doesn't have permissions

### LINKED ISSUE #9228: [Overview Page] Issue in Clusters Card with RBAC
### Describe the bug

With the following config: 

```
deployment:
  cluster_wide_access: false
  discovery_selectors:
    default:
    - matchLabels:
        kubernetes.io/metadata.name: alpha
    - matchLabels:
        kubernetes.io/metadata.name: bookinfo
```

I'm able to see the Clusters card (With wrong health) and the "View Mesh" link: 

Image

Image

### Expected Behavior
There shouldn't be Mesh links if the user doesn't have permissions to access to the mesh page.

### What are the steps to reproduce this bug?

1. …
2. …
3. …

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

Proposal for when a user doesn't have permissions in the control plane: 
image
image

- Update the icon
- Remove the "View mesh" link
- Remove the icon to the cluster (Was redirecting to the mesh page)
- Show "Unknown status" instead of "1 issue" (That was not found"

Note: I think we should made a change in the "Kubernetes" global icon so it is not shown as red? (Not addressed here)
image

When the user has permissions, the behavior doesn't change:

- If there is any component wrong: 
image

### Steps to test the PR

Recommendations for how to test this PR. Reminder that each PR should also include a "Test" label.

### Automation testing

If applicable, explain the case scencarios covered by **unit / integration / e2e** tests created for this PR.

### Issue reference

FIxes #9228

### CODE REVIEW

File: frontend/src/pages/Overview/ClusterStats.tsx [hunk 1]
```diff
@@ -21,11 +22,15 @@ import {
   statsContainerStyle
 } from './OverviewStyles';
 import { classes } from 'typestyle';
-import { ClusterIssue, isHealthy, isUnhealthy } from 'utils/StatusUtils';
+import { isHealthy, isUnhealthy } from 'utils/StatusUtils';
+import { isControlPlaneAccessible } from 'utils/MeshUtils';
 import { StatCountPopover } from './StatCountPopover';
 
+type ClusterIssue = { issues: number; name: string; unknownStatus: boolean };
```
Comment (ferhoyos) [inline frontend/src/pages/Overview/ClusterStats.tsx]: Already defined in `utils/StatusUtils`

File: frontend/src/pages/Overview/ClusterStats.tsx [hunk 2]
```diff
@@ -35,28 +40,41 @@ export const ClusterStats: React.FC = () => {
...
-        name: clusterName
+        name: clusterName,
+        unknownStatus
       });
     }
 
     return acc;
   }, [] as ClusterIssue[]);
 
+  const hasUnknownIssues = clustersWithIssues.some(c => c.unknownStatus);
```
Comment (ferhoyos) [inline frontend/src/pages/Overview/ClusterStats.tsx:57]: Here you are showing unhealthy or unknown icon. What happens if we have both unhealthy and unknown clusters? Should we show both icons in the card?

Comment (josunect) [reply frontend/src/pages/Overview/ClusterStats.tsx:57]: It is shown as part of the warning, I've though the idea was to reduce these icons: 
image

But, we can also add both

File: frontend/src/pages/Overview/ClusterStats.tsx (hunk 1 above)
Comment (josunect) [reply frontend/src/pages/Overview/ClusterStats.tsx]: Updated

File: frontend/src/pages/Overview/ClusterStats.tsx (hunk 2 above)
Comment (ferhoyos) [reply frontend/src/pages/Overview/ClusterStats.tsx:57]: We can discuss with @Joeyyubo and change later in a follow-up PR
