### PR TITLE
[ambient] fixes to waypoint capture logic

### LINKED ISSUE #8050: Allow custom waypoint gracefully
### Describe the bug

Kiali currently gave an error on bringing your own waypoint.

### Expected Behavior

I don't expect this to be an error, should be warning at the most or informational as waypoint is supposed to be plug-gable.

image

### What are the steps to reproduce this bug?

Attaching a screenshot showing the error.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: version shipped in istio 1.24.2
- **Istio version:1.24.2
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### LINKED ISSUE #8157: [ambient] Some Waypoint proxies are reported incorrectly
### Describe the bug

Some Waypoint proxies are reported incorrectly in specific configurations: 

- waypoint for none: The waypoint still appears in the workload list. 

Image

- waypoint for none: It is reported as waypoint for service in the waypoints list. 

Image

- Duplicates in the list for waypoint override:

Image
 
- There are no traces for the workloads. Probably they should use the name of the application and not the app label? 

### What are the steps to reproduce this bug?

Ref. https://github.com/kiali/kiali/pull/8156 

1. Install ambient mesh 
2. Run the hack script to install the environment: hack/istio/ambient/install-waypoints.sh (See https://github.com/kiali/kiali/pull/8156) 

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes #8157 
Fixes #8050

This PR works on the cases presented in 8157. It does revise some of the code for to [hopefully] consolidate and simplify some of the logic.
- fix the issue use cases
- improve logic for waypoint identification
- fix the Waypoint tab's default sub-tab when the waypoint is `for-none`.
- refactor `isWaypointFor` into `getCapturingWaypoints`
  - this now optionally returns only the active waypoint, or all of the capturing waypoints. Currently we return only the active waypoint because the UI doesn't have logic for presenting the inactive (overridden) waypoints.
  - add more comments explaining this complicated logic
- prefer ambient boolean flags, for clarity
  - refactor `.ambient` -> `.isWaypoint` and `.isZtunnel`
    - fix issues setting the ambient flags
    - fix UI issue showing "missing sidecar" for pod (in workload detail page)
 
To Test
- You need an ambient install
- You need to run hack/istio/ambient/install-waypoints.sh
- Test the various scenarios to ensure everything makes sense, paying close attention to waypoint capture and info, and information presented on the detail overview pages.  Also sanity check the graph and anything else you can thing of that may be influenced by ambient/waypoint/ztunnel detection.

### CODE REVIEW

File: frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx [hunk 1]
```diff
@@ -322,8 +318,7 @@ class WorkloadDetailsPageComponent extends React.Component<WorkloadDetailsPagePr
           // Ztunnel doesn't have Envoy
           hasIstioSidecars =
             hasIstioSidecars ||
-            (!!pod.containers &&
-              pod.containers.some(cont => cont.name === istioProxyName && workload.ambient !== 'ztunnel'));
+            (!!pod.containers && pod.containers.some(cont => cont.name === istioProxyName && workload.isZtunnel));
```
Comment (josunect) [inline frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx:321]: That should be !workload.isZtunnel, so the Envoy tab is hidden for ztunnel: 

image

**Review by josunect — COMMENTED** [review]
@jshaughn , I think this is looking good, I've validated the logic in the graph and the details: 

image

I see this might be incorrect: The services list from a waypoint are including the waypoint services as well, IMO this should be removed:

image

(Waypoint and use-this are Waypoints themselves)

Additionally to this PR, I think it would nice to have cypress coverage for all these use-cases

File: frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx (hunk 1 above)
Comment (jshaughn) [reply frontend/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx:321]: Nice catch, thanks!

**Comment by jshaughn** [comment]
> I see this might be incorrect: The services list from a waypoint are including the waypoint services as well, IMO this should be removed

@josunect ,
+1. I've pushed this change as well as some other changes and fixes.  I don't have anything else pending, so please take another look when you are able.

**Review by josunect — COMMENTED** [review]
LG! 

This might be outside as this PR, but I've realized that even if a workload doesn't have a waypoint, it is shown the waypoint check in the workload log details, but if it doesn't have a waypoint and you click on it, you receive an error, it might be fixed here: 

https://github.com/kiali/kiali/blob/master/frontend/src/pages/WorkloadDetails/WorkloadPodLogs.tsx#L598

with this change:
`{(this.props.waypoints && this.props.waypoints.length > 0) && (`

**Review by josunect — APPROVED** [review]
LG!

I can do the mentioned changes in another PR

**Comment by jshaughn** [comment]
> This might be outside as this PR, but I've realized that even if a workload doesn't have a waypoint, it is shown the waypoint check in the workload log details, but if it doesn't have a waypoint and you click on it, you receive an error, it might be fixed here

Another good find, there are so many cases to handle!  I will merge this as-is and you can follow up with a separate PR, thanks!
