### PR TITLE
[ambient graph] Fix HTTP traffic loss when disabling TCP traffic

### LINKED ISSUE #7549: Hiding TCP hides HTTP
I have a setup with ambient and waypoints. Kiali v1.87.

If I display all traffic, its fine (shows TCP+HTTP). if I hide HTTP traffic, its fine (shows TCP). If I hide TCP, it hides HTTP as well unexpectedly

Both visible

Hiding TCP

Hiding HTTP

My HTTP metrics:
```

istio_requests_total{connection_security_policy="mutual_tls", destination_app="unknown", destination_canonical_revision="unknown", destination_canonical_service="unknown", destination_cluster="Kubernetes", destination_principal="unknown", destination_service="httpbin.org", destination_service_name="httpbin.org", destination_service_namespace="istio-egress", destination_version="unknown", destination_workload="unknown", destination_workload_namespace="unknown", gateway_istio_io_managed="istio.io-mesh-controller", gateway_networking_k8s_io_gateway_name="waypoint", instance="10.244.0.24:15020", istio_io_dataplane_mode="none", job="kubernetes-pods", namespace="istio-egress", node="kind-control-plane", pod="waypoint-6c6b888f4f-wmnr2", pod_template_hash="6c6b888f4f", reporter="waypoint", request_protocol="http", response_code="200", response_flags="-", service_istio_io_canonical_name="waypoint", service_istio_io_canonical_revision="latest", sidecar_istio_io_inject="false", source_app="shell", source_canonical_revision="latest", source_canonical_service="shell", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/default", source_version="latest", source_workload="shell", source_workload_namespace="default"}
```

TCP:
```

istio_tcp_connections_opened_total{app="ztunnel", connection_security_policy="mutual_tls", controller_revision_hash="68558758d7", destination_app="waypoint", destination_canonical_revision="latest", destination_canonical_service="waypoint", destination_cluster="Kubernetes", destination_principal="spiffe://cluster.local/ns/istio-egress/sa/waypoint", destination_service="httpbin.org", destination_service_name="httpbin.org", destination_service_namespace="istio-egress", destination_version="latest", destination_workload="waypoint", destination_workload_namespace="istio-egress", instance="10.244.0.15:15020", istio_io_dataplane_mode="none", job="kubernetes-pods", namespace="istio-system", node="kind-control-plane", pod="ztunnel-zxrxk", pod_template_generation="2", reporter="source", request_protocol="tcp", response_flags="-", sidecar_istio_io_inject="false", source_app="shell", source_canonical_revision="latest", source_canonical_service="shell", source_cluster="Kubernetes", source_principal="spiffe://cluster.local/ns/default/sa/default", source_version="latest", source_workload="shell", source_workload_namespace="default"}
```

### PR DESCRIPTION
**Pull request by jshaughn**
Fixed #7549 

Fix issue where we mistakenly discarded http edges when tcp edges weren't also in the graph (and therefore no edges to/from waypoints).  The fix could have been centered around fixing the initialization of

`graphEdge := []*graph.Edge{}`

to preserve non-tcp edges.  But the code was a little confusing to me, so this reworks things a bit to [hopefully] make it more simple.

@josunect ,  this should solve the reported bug but there will still be follow-on work to do.  We can still think more about waypoint visualization.  With this, if you add in waypoints you can see them but it's uni-directional.  Also, you may notice that if you remove service nodes you mostly lose TCP visualization, also related to waypoint handling/ztunnel reporting.

To test, this is fairly easy to see with bookinfo demo, especially in node graphs.  But it could be reproduced in other ways.

### CODE REVIEW

File: graph/telemetry/istio/appender/ambient.go [hunk 1]
```diff
@@ -39,67 +40,57 @@ func (a AmbientAppender) AppendGraph(trafficMap graph.TrafficMap, globalInfo *gr
...
+		for _, n := range trafficMap {
+			n.Edges = sliceutil.Filter(n.Edges, func(edge *graph.Edge) bool {
+				return !deletedWaypoints[edge.Dest.ID]
+			})
 		}
-		n.Edges = graphEdge
 	}
 }
 
+/* Currently not needed as it no longer protects against an invalid backend call.
```
Comment (josunect) [inline graph/telemetry/istio/appender/ambient.go:85]: That could be removed?

**Review by josunect — APPROVED** [review]
LGTM! 
image

image

I will create a follow up task with the indications in the comment.
I think this scenario could be included in the e2e tests.
