### PR TITLE
Autodetect the istiod monitoring port

### LINKED ISSUE #8553: Detect monitoring port for each controlplane
### Describe the bug

Kiali has a [single config option](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.istio.istiod_pod_monitoring_port) for every controlplane's monitoring port. When each controlplane in a mesh has custom monitoring ports, Kiali won't be able to connect to the correct one.

### Expected Behavior

Kiali can connect to each controlplane's monitoring port without having to set the config option.

### What are the steps to reproduce this bug?

1. Create an Istio instance with a custom monitoring port
2. Check Kiali logs for errors autodetecting the mesh.

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version: 2.12**
- **Istio version: 1.26**
- **Kubernetes impl: vanilla** 
- **Kubernetes version: 1.32** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by nrfox**
### Describe the change

- Autodetects the monitoring port instead of assuming it is the default `15014`.
  - Does this by parsing the istiod args for what is passed in the `--monitoringAddr` cmd line flag. This could have come from the deployment's ports but there's no guarantee that what is set there matches what gets passed as an arg.
- Removes the `IstiodPodMonitoringPort` config setting as part of https://github.com/kiali/kiali/issues/8576
- Adds structured logging to the control plane monitor and properly passes context through
  ```
  2025-07-28T19:06:32Z DBG Getting proxy status from istiod cluster=cluster-default component=controlplane-monitor revision=default
  E0728 19:06:32.081872       1 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 14052 -> 15014: error forwarding port 15014 to pod e923ef14bb694b71d6af119137700f972920ae12f0f69893a91cf3234073659a, uid : failed to execute portforward in network namespace \"/var/run/netns/cni-ea075663-99be-51d7-b4c0-8b1bafc23559\": failed to connect to localhost:15014 inside namespace \"e923ef14bb694b71d6af119137700f972920ae12f0f69893a91cf3234073659a\", IPv4: dial tcp4 127.0.0.1:15014: connect: connection refused IPv6 dial tcp6 [::1]:15014: connect: connection refused " logger="UnhandledError"
  2025-07-28T19:06:32Z ERR Failed to call Istiod endpoint /debug/syncz error: Error fetching the proxy-status in the following pods: istiod-5547bc8d48-z89xg: Get "http://localhost:14052/debug/syncz": EOF cluster=cluster-default component=controlplane-monitor revision=default
  ```

### Steps to test the PR

Somewhat convoluted testing instructions since the sail operator doesn't support overlay manifests yet.

1. Build / deploy PR in test environment
  ```
  make build-ui build && ./hack/run-integration-tests.sh --test-suite backend --setup-only true
  ```

2. Scale down Sail Operator replicas to 0 (otherwise the operator will overwrite changes)
  ```
  kubectl scale deployment -n sail-operator --replicas=0 sail-operator
  ```
3. Update the monitoring port to something other than default on both the istiod service and the istiod deployment
4. Ensure no error logs in Kiali

### Automation testing

Unit tests included

### Issue reference

Fixes #8553

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -331,7 +331,6 @@ type IstioConfig struct {
 	IstioSidecarInjectorConfigMapName string            `yaml:"istio_sidecar_injector_config_map_name,omitempty" json:"istioSidecarInjectorConfigMapName,omitempty"`
 	IstioSidecarAnnotation            string            `yaml:"istio_sidecar_annotation,omitempty" json:"istioSidecarAnnotation,omitempty"`
 	IstiodDeploymentName              string            `yaml:"istiod_deployment_name,omitempty" json:"istiodDeploymentName,omitempty"`
-	IstiodPodMonitoringPort           int               `yaml:"istiod_pod_monitoring_port,omitempty" json:"istiodPodMonitoringPort,omitempty"`
```
Comment (josunect) [inline config/config.go]: Should this be removed from the operator as well?

**Review by josunect — DISMISSED** [review]
Verified, updating the port: 

image
image

no Kiali errors in UI or logs: 
image

In master, I found the error: 
```
E0731 11:58:33.145341       1 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 14016 -> 15014: error forwarding port 15014 to pod 08d56b85d6f0f503fad41a0bccd2148b937e3e979dc419be8104939f20d8f719, uid : failed to execute portforward in network namespace \"/var/run/netns/cni-9707338d-61a4-1369-f954-7c03246c1dcc\": failed to connect to localhost:15014 inside namespace \"08d56b85d6f0f503fad41a0bccd2148b937e3e979dc419be8104939f20d8f719\", IPv4: dial tcp4 127.0.0.1:15014: connect: connection refused IPv6 dial tcp6 [::1]:15014: connect: connection refused " logger="UnhandledError"
2025-07-31T11:58:33Z ERR Failed to call Istiod endpoint /debug/registryz error: Error fetching the proxy-status in the following pods: istiod-86cdc5c884-fhgdx: Get "http://localhost:14016/debug/registryz": EOF
2025-07-31T11:58:33Z WRN Error getting proxy status from istiod. Proxy status may be stale. Err: <nil>
2025-07-31T11:58:35Z TRC [ValidationsReconciler] Started reconciling 
```

Code lgtm, just a comment

File: config/config.go (hunk 1 above)
Comment (nrfox) [reply config/config.go]: Yes I'll add the "needs operator" and "needs docs" label to the PR

**Comment by nrfox** [comment]
Had to rebase due to some conflicts

**Comment by jmazzitelli** [comment]
I added this to the operator PR that is removing auto-detected things:
* https://github.com/kiali/kiali-operator/pull/941
