### PR TITLE
Fix race condition in kube cache by locking sooner

### LINKED ISSUE #6641: data race - GetKialiTokenForHomeCluster
Saw this in a CI run - just documenting it now so I don't lose it. If this really isn't an issue, just close this. But we should at least quickly review the affected code.

```
==================
WARNING: DATA RACE
Read at 0x000004[49](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:50)91b0 by goroutine 396:
  github.com/kiali/kiali/kubernetes.GetKialiTokenForHomeCluster()
      /home/runner/work/kiali/kiali/kubernetes/token.go:24 +0x3e
  github.com/kiali/kiali/kubernetes.(*clientFactory).refreshClientIfTokenChanged()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:411 +0x2c9
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:395 +0x70
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAHomeClusterClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:456 +0x49
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1.1.1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:43 +0x97
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:62 +0x7b
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:63 +0x2a7
  k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/poll.go:33 +0x70
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1.1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:41 +0x164
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:57 +0x64

Previous write at 0x0000044991b0 by goroutine 397:
  github.com/kiali/kiali/kubernetes.GetKialiTokenForHomeCluster()
      /home/runner/work/kiali/kiali/kubernetes/token.go:37 +0x12a
  github.com/kiali/kiali/kubernetes.(*clientFactory).refreshClientIfTokenChanged()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:411 +0x2c9
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:395 +0x70
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAHomeClusterClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:456 +0x49
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).watchForClientChanges.func1()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:182 +0x13b

Goroutine 396 (running) created at:
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:22 +0x10e
  github.com/kiali/kiali/kubernetes/cache.NewKialiCache()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:129 +0x611
  github.com/kiali/kiali/business.initKialiCache()
      /home/runner/work/kiali/kiali/business/layer.go:66 +0x2c4
  github.com/kiali/kiali/business.Start()
      /home/runner/work/kiali/kiali/business/layer.go:91 +0x44
  github.com/kiali/kiali/server.(*Server).Start()
      /home/runner/work/kiali/kiali/server/server.go:92 +0x45
  main.main()
      /home/runner/work/kiali/kiali/kiali.go:112 +0x57b

Goroutine 397 (running) created at:
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).watchForClientChanges()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:178 +0x1d4
  github.com/kiali/kiali/kubernetes/cache.NewKialiCache()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:135 +0x656
  github.com/kiali/kiali/business.initKialiCache()
      /home/runner/work/kiali/kiali/business/layer.go:66 +0x2c4
  github.com/kiali/kiali/business.Start()
      /home/runner/work/kiali/kiali/business/layer.go:91 +0x44
  github.com/kiali/kiali/server.(*Server).Start()
      /home/runner/work/kiali/kiali/server/server.go:92 +0x45
  main.main()
      /home/runner/work/kiali/kiali/kiali.go:112 +0x57b
==================
==================
WARNING: DATA RACE
Read at 0x00000449c320 by goroutine 396:
  github.com/kiali/kiali/kubernetes.shouldRefreshToken()
      /home/runner/work/kiali/kiali/kubernetes/token.go:[50](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:51) +0x64
  github.com/kiali/kiali/kubernetes.GetKialiTokenForHomeCluster()
      /home/runner/work/kiali/kiali/kubernetes/token.go:24 +0x33
  github.com/kiali/kiali/kubernetes.(*clientFactory).refreshClientIfTokenChanged()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:411 +0x2c9
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:395 +0x70
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAHomeClusterClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:4[56](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:57) +0x49
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1.1.1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:43 +0x97
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:62 +0x7b
  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/loop.go:63 +0x2a7
  k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel()
      /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/wait/poll.go:33 +0x70
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1.1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:41 +0x164
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus.func1()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:57 +0x64

Previous write at 0x00000449c320 by goroutine 397:
  github.com/kiali/kiali/kubernetes.GetKialiTokenForHomeCluster()
      /home/runner/work/kiali/kiali/kubernetes/token.go:39 +0x337
  github.com/kiali/kiali/kubernetes.(*clientFactory).refreshClientIfTokenChanged()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:411 +0x2c9
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:395 +0x70
  github.com/kiali/kiali/kubernetes.(*clientFactory).GetSAHomeClusterClient()
      /home/runner/work/kiali/kiali/kubernetes/client_factory.go:456 +0x49
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).watchForClientChanges.func1()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:182 +0x13b

Goroutine 396 (running) created at:
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).pollIstiodForProxyStatus()
      /home/runner/work/kiali/kiali/kubernetes/cache/proxy_status.go:22 +0x10e
  github.com/kiali/kiali/kubernetes/cache.NewKialiCache()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:129 +0x611
  github.com/kiali/kiali/business.initKialiCache()
      /home/runner/work/kiali/kiali/business/layer.go:66 +0x2c4
  github.com/kiali/kiali/business.Start()
      /home/runner/work/kiali/kiali/business/layer.go:91 +0x44
  github.com/kiali/kiali/server.(*Server).Start()
      /home/runner/work/kiali/kiali/server/server.go:92 +0x45
  main.main()
      /home/runner/work/kiali/kiali/kiali.go:112 +0x[57](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:58)b

Goroutine 397 (running) created at:
  github.com/kiali/kiali/kubernetes/cache.(*kialiCacheImpl).watchForClientChanges()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:178 +0x1d4
  github.com/kiali/kiali/kubernetes/cache.NewKialiCache()
      /home/runner/work/kiali/kiali/kubernetes/cache/cache.go:135 +0x[65](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:66)6
  github.com/kiali/kiali/business.initKialiCache()
      /home/runner/work/kiali/kiali/business/layer.go:[66](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:67) +0x2c4
  github.com/kiali/kiali/business.Start()
      /home/runner/work/kiali/kiali/business/layer.go:[91](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:92) +0x44
  github.com/kiali/kiali/server.(*Server).Start()
      /home/runner/work/kiali/kiali/server/server.go:[92](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:93) +0x45
  main.main()
      /home/runner/work/kiali/kiali/kiali.go:[112](https://github.com/kiali/kiali/actions/runs/6236835841/job/16929649550?pr=6629#step:9:113) +0x57b
```

### PR DESCRIPTION
**Pull request by nrfox**
Fixes #6641

### CODE REVIEW

File: business/tls_test.go [hunk 1]
```diff
@@ -537,7 +538,7 @@ func fakeStrictMeshPeerAuthentication(name string) []*security_v1.PeerAuthentica
 
 func fakeMeshPeerAuthenticationWithMtlsMode(name, mTLSmode string) []*security_v1.PeerAuthentication {
 	mtls := &api_security_v1.PeerAuthentication_MutualTLS{
-		Mode: api_security_v1.PeerAuthentication_MutualTLS_Mode(api_security_v1.PeerAuthentication_MutualTLS_Mode_value[mTLSmode]),
+		Mode: api_security_v1.PeerAuthentication_MutualTLS_Mode(api_security_v1beta1.PeerAuthentication_MutualTLS_Mode_value[mTLSmode]),
```
Comment (hhovsepy) [inline business/tls_test.go:541]: @nrfox what's the reason behind using those enum constants from older api versions? aren't they both constants without locks?

Comment (nrfox) [reply business/tls_test.go:541]: Since I updated the istio libraries from 1.22 --> 1.24, these constants no longer exist in `api_security_v1` but they still exist in `api_security_v1beta1`.

**Review by hhovsepy — APPROVED** [review]
lgtm, tested on Jenkins CI and locally
