### PR TITLE
Fix double revision in istio configmap name

### LINKED ISSUE #6669: Double istio rev in configmap name
Hello.

istio installed via helm

```
  values:
    revision: "1-18-0"
```

kiali

```
  values:
    allowAdHocKialiImage: true
    resources:
      limits:
        cpu: 1
    cr:
      create: true
      namespace: istio-system
      spec:
        istio_namespace: istio-system
        external_services:
          istio:
            config_map_name: "istio-1-18-0"
            istiod_deployment_name: "istiod-1-18-0"
            istio_sidecar_injector_config_map_name: "istio-sidecar-injector-1-18-0"
```

i receive this error from kiali log.

`ERR Error getting mesh config: configmap "istio-1-18-0-1-18-0" not found`

i do not understand why rev is doubled in configmap name?

### PR DESCRIPTION
**Pull request by nrfox**
Uses: `conf.ExternalServices.Istio.ConfigMapName` without adding the rev tag when it is set and not the default `istio`.

Fixes #6669

### CODE REVIEW

**Comment by nrfox** [comment]
@jmazzitelli please take a look at this when you get a chance

**Review by jmazzitelli — CHANGES_REQUESTED** [review]
This code change makes sense. We need to make the call to this new IstioConfigMap name in all the places where we need the name.

These places: https://github.com/search?q=repo%3Akiali%2Fkiali+%2FGetConfigMap.*ExternalServices.Istio.ConfigMapName%2F&type=code

Here's the files that probably need to be changed in this PR:

```
$ grep -Rl ExternalServices.Istio.ConfigMapName *
business/istio_certs.go
business/namespaces.go
business/tls.go
business/istio_validations.go
business/mesh.go
handlers/config.go
```

Note that this PR directly addresses [this issue](https://github.com/kiali/kiali/issues/6042) too - so we can close this issue when this PR is merged.

**Comment by yohanb** [comment]
@nrfox thanks for this PR!  We just ran into this issue and traced it back to the same faulty code.
When can we expect this to be complete?  Only missing a few refactors ;)

**Comment by nrfox** [comment]
> @nrfox thanks for this PR! We just ran into this issue and traced it back to the same faulty code.
> When can we expect this to be complete? Only missing a few refactors ;)

@yohanb hoping to have this complete by the end of the week so it can be included with the next release.

**Comment by yohanb** [comment]
> > @nrfox thanks for this PR! We just ran into this issue and traced it back to the same faulty code.
> > When can we expect this to be complete? Only missing a few refactors ;)
> 
> @yohanb hoping to have this complete by the end of the week so it can be included with the next release.

Awesome, thanks so much 👍

**Comment by nrfox** [comment]
@jmazzitelli it seemed like the e2e tests were failing because of the tracing flakes. I rebased with main to pickup the latest fix. I also added some additional test coverage to the area that was causing this error to be logged which was in gateway validations.

File: business/mesh.go [hunk 1]
```diff
@@ -155,10 +155,7 @@ func (in *MeshService) GetMesh(ctx context.Context) (*Mesh, error) {
 					Revision: istiod.Labels[IstioRevisionLabel],
 				}
 
-				configMapName := in.conf.ExternalServices.Istio.ConfigMapName
-				if revLabel := istiod.Labels[IstioRevisionLabel]; revLabel != "default" && revLabel != "" {
-					configMapName = configMapName + "-" + revLabel
-				}
+				configMapName := IstioConfigMapName(in.conf, controlPlane.Revision)
```
Comment (jmazzitelli) [inline business/mesh.go:158]: the thing I don't see explained anywhere here is why does this pass in the Revision but everywhere else it passes in empty string for revision. How does this work when sometimes you need the revision but other times that is not required to get the configmap?

**Review by jmazzitelli — APPROVED** [review]
this does the refactor so everywhere in the code gets the configmap name using the common function. I have a feeling our support for canary upgrades still isn't seamless but we can worry about that later.

File: business/mesh.go (hunk 1 above)
Comment (nrfox) [reply business/mesh.go:158]: Because basically this is the only place that is handling there being multiple controlplanes. Everywhere else just assumes there's one. When set `config.external_services.istio.config_map_name`, `IstioConfigMapName` will always return what you've set there regardless of what revision you pass in. It's a bit of a hack to get around the fact that, right now we expect users to set this manually when using control plane revisions.

**Comment by nrfox** [comment]
> I have a feeling our support for canary upgrades still isn't seamless but we can worry about that later.

Yes this change doesn't make the support for canary upgrades any better but it at least gets rid of the error log when you've set `config.external_services.istio.config_map_name`.

**Comment by amazingandyyy** [comment]
good to see this get merged, what's the ETA for new helm chart release? thanks for the hard work!

**Comment by yohanb** [comment]
probably removing the logic to append the revision all together would be a more cohesive solution.  I think we can simply expect users to provide the correct values through `external_services.istio`

**Comment by jmazzitelli** [comment]
> probably removing the logic to append the revision all together would be a more cohesive solution. I think we can simply expect users to provide the correct values through `external_services.istio`

I'm OK doing either suggestion. if Kiali users like @yohanb think it would be simpler and expected of users to set the correct value in the Kiali config, then let's do that.

cc @nrfox

**Comment by nrfox** [comment]
> I'm OK doing either suggestion. if Kiali users like @yohanb think it would be simpler and expected of users to set the correct value in the Kiali config, then let's do that.

That sounds good to me. The only place that is currently using the offending code from `GetMesh` does not use the config map anyways and I'd rather be sure to not break existing functionality or cause noise for users. I appreciate the feedback here and it's very useful knowing that this is config that users rely on.

**Comment by jmazzitelli** [comment]
we need to backport this to the 1.73 branch.
