### PR TITLE
For Argo rollout, use the controller's replica sets as workloads

### LINKED ISSUE #4210: "KIA0203 This subset's labels are not found in any matching host" For Argo Rollout canary scenario
During canary rollout with Argocd with subset-traffic splitting: https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/#subset-level-traffic-splitting

One of the destination is marked as: "KIA0203 This subset's labels are not found in any matching host", however its live and istio routes traffic correctly.
Screen Shot 2021-07-23 at 3 03 45 PM

Istio routes traffic fine to both destinations and pods with labels from destination rule are available as well
```
$kubectl get pods -l app=example,rollouts-pod-template-hash=6fd44bcc96
NAME                       READY   STATUS    RESTARTS   AGE
example-6fd44bcc96-csqrf   2/2     Running   0          6h2m

 $kubectl get pods -l app=example,rollouts-pod-template-hash=64db898946
NAME                       READY   STATUS    RESTARTS   AGE
example-64db898946-hxq22   2/2     Running   0          23m
```
**Versions used**
Kiali: 1.37.0
Istio: 1.8.1
Kubernetes flavour and version: AKS 1.20

**To Reproduce**
1. Set up Canary Release with subset-level traffic splitting: https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/#subset-level-traffic-splitting
2. Trigger Canary rollout
3. Check destination rule in Kiali

**Expected behavior**
Subset should be available in Kiali.

output of: `curl 'http://<kiali>/kiali/api/namespaces/example-dev/istio/destinationrules/example?validate=true'`
[out.txt](https://github.com/kiali/kiali/files/6871414/out.txt)

### PR DESCRIPTION
**Pull request by jshaughn**
For a custom controller that manages replica sets (like Argo Rollout), defer to the replica sets as the workloads, and not the custom controller. The controller may control multiple replica sets, it may not live in the same namespace as the replica sets, and it may have unusual characteristics. But maybe most importantly, Istio telemetry will report the RS as the workload, and so it is critical to the graph, and linking, to use the RS as the workload.

Closes https://github.com/kiali/kiali/issues/5261
Closes #4210

### CODE REVIEW

File: business/workloads.go [hunk 1]
```diff
@@ -1370,12 +1380,12 @@ func fetchWorkload(ctx context.Context, layer *Layer, criteria WorkloadCriteria)
 	// Resolve ReplicaSets from Deployments
 	// Resolve ReplicationControllers from DeploymentConfigs
 	// Resolve Jobs from CronJobs
-	for cname, ctype := range controllers {
-		if ctype == kubernetes.ReplicaSetType {
+	for controllerName, controllerType := range controllers {
+		if controllerType == kubernetes.ReplicaSetType {
 			found := false
 			iFound := -1
 			for i, rs := range repset {
```
Comment (leandroberetta) [inline business/workloads.go:1387]: I didn't test this yet, but when debugging with the Argo Rollout installed, with two ReplicaSets belonging to it, one of the RS was discarded because it is missing in the repset variable. This is because the GetReplicaSet method only returns one of the ReplicaSets belonging to the Rollout. 

Are you seeing both RS on the Workloads List?.

**Review by leandroberetta — APPROVED** [review]
LGTM. Tested locally and solves #4210

File: business/workloads.go (hunk 1 above)
Comment (jshaughn) [reply business/workloads.go:1402]: This was resolved.
