### PR TITLE
Skip validation checkers when there are no config changes

### LINKED ISSUE #8007: Kiali uses a lot of CPU (in validations)
### Describe the bug

On a cluster with around 1600 namespaces, but a discovery selector that only selects around 380 of them and cluster wide view set to true, the CPU usage of the Kiali pod is permanently around 2500m. Although I have no reference to compare it with, this seems a bit excessive. This is even with any clients interacting with the UI.

image

The graph shows a drop in usage. With cluster wide view disabled, CPU load is around 4000m.

### Expected Behavior

I'd like to understand if this a reasonable amount of CPU for our setup or if there is an issue with Kiali that causes it to use so much CPU.

### What are the steps to reproduce this bug?

Nothing in particular.
Cluster has around 1600 namespaces in total, but only 380 are selected with a discovery selector. Cluster wide view is enabled. Anonymous mode enabled.

### Environment

- **Kiali version:** 2.2.0
- **Istio version:** 1.23.2 asm 2
- **Kubernetes impl:** GKE
- **Kubernetes version:** 1.30
- **Other notable environmental factors:**

Issues/PRs for this Epic:
- [x] https://github.com/kiali/kiali/pull/8119
- [x] https://github.com/kiali/kiali/pull/8194
- [x] https://github.com/kiali/kiali/pull/8206
- [x] #8211 
- [x] #8210 
- [ ] [pre-compute validation keys for istio config objects](https://github.com/kiali/kiali/pull/8335)

### PR DESCRIPTION
**Pull request by jshaughn**
Part-of #8007 

The idea here is to generate a hash for config used in validations, using config ResourceVersion where applicable, and otherwise hashing relevant checker information. For example, we can't use Workload ResourceVersion because it changes when status is updated (and so is sensitive to pods coming and going). If the hash does not change at validation Reconcile time, then skip running the checkers.

This solution is something of a trade-off. It avoids the complexity needed for callback-based watchers on config, or other very granular approaches. But each reconcile still needs to gather the related config, and generate the hash. The savings is in being able to avoid running the checkers.  In the data presented in #8007 the checkers accounted for a lot of the validation time, so the hope is that this will be helpful, and push off any need to do something more complicated.

The algorithm works like this:

```
For base config (used for cross-cluster validation)
  generate a hash for the config (basically workload config)

For each cluster:
  generate a hash for the config defined in that cluster (services, all of the istio config)
  if hash is different or there is a base config change
    run checkers for the cluster
    replace previous validations
  else 
    keep previous validations
```

This also introduces a hidden config option to enable or disable this logic (default is enabled). The option is mainly a fail-safe, just in case we find a flaw in the logic that prevents validation re-generation, or somehow ends up adding to resource consumption.

Operator PR: https://github.com/kiali/kiali-operator/pull/885

### CODE REVIEW

**Comment by jshaughn** [comment]
@hhovsepy , @nrfox , I created a POC here to see if this approach seemed feasible and worthwhile.  Before moving forward I wanted to get your feedback on approach, or other general comments.  We could have a short meeting, or you could drop comments here...

**Comment by nrfox** [comment]
Where this is most needed for performance gains, large clusters with lots of config/workloads/services, I don't think this approach will provide enough of a perf gain in practice because workloads in particular will be constantly changing so the odds of the validations being skipped will be low. The resource version changes even when the status updates on an object so pods coming and going would invalidate the hash.

This would be more work to setup initially but if we can validate a single object when it changes or when any of it's related objects change rather than looking at every object and processing all validations when a single object changes that would be much more efficient. Some changes in objects we also don't care about and it would be good to filter those out too. We probably only care if the `spec` changes on various objects but not the `status` for validations.

**Comment by nrfox** [comment]
The current way the validations controller processes validations where it processes all validations on a timer was the simplest way to get started but is by no means the most efficient way of doing it.

**Comment by hhovsepy** [comment]
It can be a very useful approach in reducing the load on CPU by validation reconciliation, so instead of configuring longer reconcile intervals, we can keep it shorter, but do not trigger validation process when nothing changed.

**Comment by jshaughn** [comment]
>  The resource version changes even when the status updates on an object so pods coming and going would invalidate the hash.

OK, that's super annoying, and I didn't expect that behavior.  I thought ResourceVersion was independent of status.  But I agree that pods coming and going would mostly remove the benefit in a large production env.  The intent was to capture an actual change that could affect validation.

I agree that the `spec` is what we care about.  I suppose we could hash `Spec` at workload fetch time.  This would add some overhead when populating the cache, but it's feasible.  In essence, we'd be creating our own "WorkloadSpecVersion" field.  I think that would be the only way forward with this approach.

Single object validation granularity is probably feasible, but definitely tricky, given the references and the fact that a lot of information can be required to validate even one object. Like everything, this comes down to effort and payoff, it's not clear to me that the most performant solution is required, at least not yet.  We could just stop here and push out the optimizations in the PR we just completed, or I could go forward with this and try hashing workload `spec`.  Not sure I want to bite off more without more user feedback.

<rant>why did k8s not make it easier to detect non-status workload changes!</rant>

**Comment by jshaughn** [comment]
So, here's an interesting thing.  I started digging down into the checkers and what they do with workloads.  And from what I can tell, the only information that is used in validation checkers, aside from immutable stuff like name, namespace, gvk, are the labels.  So actually, the only real change to a workload that we'd need to detect is a change to its labels.

File: controller/validations.go [hunk 1]
```diff
@@ -96,6 +96,8 @@ type ValidationsReconciler struct {
 	validationsService *business.IstioValidationsService
 }
 
+var changeMap = map[string]string{}
```
Comment (nrfox) [inline controller/validations.go:99]: This should not be a global var. See comments above about making the changemap internal to `ValidationInfo` but either way we'll need to save some state about the current hash. This should go into the Kiali cache. Not the whole `validationInfo` object but at least the hash, I guess per cluster. `cache.Validations()` could return an object that has the hash(es) in there along with the validations, for example.

Comment (jshaughn) [reply controller/validations.go:99]: +1, I knew it had to change, I just wasn't sure what plumbing to do, and so left it easy for the POC.  Before more work I'd like @hhovsepy to run another one of his perf comparisons, to see what's what...

File: kubernetes/types.go [hunk 2]
```diff
@@ -252,7 +252,8 @@ type IstioService struct {
 		Port     int    `json:"port"`
 		Protocol string `json:"protocol,omitempty"`
 	} `json:"ports"`
-	Hostname string `json:"hostname"`
+	Hostname        string `json:"hostname"`
+	ResourceVersion string `json:"ResourceVersion"`
```
[the remark this answers is not in the document]
Comment (jshaughn) [reply kubernetes/types.go:256]: https://github.com/istio/istio/blob/master/pilot/pkg/model/service.go#L125

File: controller/validations.go (hunk 1 above)
Comment (hhovsepy) [reply controller/validations.go:99]: rerunning the pref test on this PR

**Comment by jshaughn** [comment]
@nrfox @hhovsepy OK, given our discussion and some initial perf delta results, I'm going to flesh out the POC today, it seems worthwhile...

**Comment by nrfox** [comment]
> From Istio config list perspective it is more or less the same results. However considering that the optimization is in backend process. The rest of results can be env instability issues. Figure_1

@jshaughn based on this ^^ it doesn't seem like the optimization will have much impact. Although like @hhovsepy mentioned there is a lot of variability in the results due to the environment and what we are testing.

**Comment by jshaughn** [comment]
> I think our cypress perf tests are not the right ones to check on this PR. It requires a pprof comparison of long running perf environment.

I agree, I'm not sure this is best measured by these tests.  Remember that this does not affect individual object validations, only the full validation reconciles.  So, impact may be harder to measure, it's mostly about overall server resource usage.

**Comment by hhovsepy** [comment]
The measurement can be in this scenario:
Start pprof monitoring.
Start perf tests.
Leave the env after perf tests finishes.
Stop pprof monitoring.
Measure the results and compare before/after this PR.
For this I think we need this PR rebased with master for the the benchmark tests merged today.

File: business/istio_validations.go [hunk 3]
```diff
@@ -142,27 +149,34 @@ type validationInfo struct {
...
 	// clusterInfo is reset for each cluster being validated
 	clusterInfo *validationClusterInfo
+
 	// nsInfo is reset for each namespace being validated (for the cluster being validated)
 	nsInfo *validationNamespaceInfo
+
+	// changeMap is used to store "hashes" of config resourceVersion information. It can be supplied
+	// to NewValidationInfo() and used on subsequent runs to check for changes and eliminate checker runs
+	// when nothing significant has changed. If not supplied then no change detection is performed.
+	changeMap changeMap
```
[the remark this answers is not in the document]
Comment (jshaughn) [reply business/istio_validations.go]: I agree, and have added some funcs to vInfo to hide direct manipulation of the field.

File: controller/validations.go (hunk 1 above)
Comment (jshaughn) [reply controller/validations.go]: @nrfox I've moved this into the cache, let me know if it looks OK to you.

**Comment by jshaughn** [comment]
@hhovsepy , @nrfox OK, I'm going to promote this PR as I don't have any more pending work or ideas. We can run some more tests and decide whether it's worth adding.

**Comment by hhovsepy** [comment]
It seems the checking of changes in hash is too sensitive,
just started a kind cluster locally, put a log in code for `changed` and `noting changed`.
And the result is that there are more changes even though I did nothing in Istio config side directly, there are some generated objects always which we are ignoring, maybe they are considered?
Screenshot from 2025-03-06 15-48-23
Screenshot from 2025-03-06 15-40-07

**Comment by jshaughn** [comment]
@hhovsepy There was a problem with the hash construction, it wasn't properly sorting the hash additions.  I've pushed a change.

**Comment by jshaughn** [comment]
I'm having trouble proving that this hashing change detection is much better than running the checkers, at least not in the small-ish environments we're looking at...  I think it's working as intended, just not sure it's worth generating these big hashes.

File: business/workloads.go [hunk 4]
```diff
@@ -1426,19 +1428,25 @@ func (in *WorkloadService) fetchWorkloadsFromCluster(ctx context.Context, cluste
...
+				if pod.AmbientEnabled() {
+					w.WaypointWorkloads = in.GetWaypointsForWorkload(ctx, *w, false)
+				}
 			}
-		}
 
-		if cnFound {
+			// Add some precalculated fields useful for validation
+			w.ValidationKey = fmt.Sprintf("%s:%s:%s", w.Cluster, w.Namespace, w.Name)
+
```
[the remark this answers is not in the document]
Comment (hhovsepy) [reply business/workloads.go:1446]: We need this missing ServiceAccountNames for the failing integration tests.

**Comment by hhovsepy** [comment]
Tested locally, tried all possible CRUDs for Istio Configs, Workloads and Services from Kiali UI and from kubectl.
The changes are recognized correctly, and validations are recalculated, otherwise when no changes done, the re-validation is skipped.
The cypress perf suite did not find neither regression nor  improvements, which are not expected on UI loading side.
The code looks good in it's idea's scope, just one small change request for fixing the ServiceAccounts for the failing integration test.
Did not run pprof yet, however it is clear that skipping the recalculation of validations will save a CPU.
One question here: In comparison, what is the load percentage on CPU and Memeory the loading and hashing all resources VS the Validation calculation itself? TODO here to run pprof.

**Comment by hhovsepy** [comment]
Rerun on the latest changes:
Screenshot from 2025-03-10 15-09-17

**Comment by jshaughn** [comment]
> Rerun on the latest changes:

Excellent,  consistent with the prior run. Thanks, @hhovsepy .  I'm going to make the enable/disable config public with a small operator PR (default will be enabled).  But I think this PR can move to final review.  cc @nrfox .

File: config/config.go [hunk 5]
```diff
@@ -321,10 +321,11 @@ type IstioConfig struct {
...
 	// proxy status and registry services. Polling is not performed if IstioAPIEnabled is false.
-	IstiodPollingIntervalSeconds int             `yaml:"istiod_polling_interval_seconds,omitempty"`
-	Registry                     *RegistryConfig `yaml:"registry,omitempty"`
-	RootNamespace                string          `yaml:"root_namespace,omitempty"`
-	UrlServiceVersion            string          `yaml:"url_service_version"`
+	IstiodPollingIntervalSeconds     int             `yaml:"istiod_polling_interval_seconds,omitempty"`
+	Registry                         *RegistryConfig `yaml:"registry,omitempty"`
+	RootNamespace                    string          `yaml:"root_namespace,omitempty"`
+	UrlServiceVersion                string          `yaml:"url_service_version"`
+	ValidationChangeDetectionEnabled bool            `yaml:"validation_hashing_enabled,omitempty"`
```
Comment (hhovsepy) [inline config/config.go:328]:
```suggestion
	ValidationChangeDetectionEnabled bool            `yaml:"validation_change_detection_enabled,omitempty"`
```

File: controller/validations.go [hunk 6]
```diff
@@ -114,10 +115,15 @@ func (r *ValidationsReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+	newValidations := make(models.IstioValidations)
+	prevValidations := r.kialiCache.Validations().Items()
+	var changeMap business.ValidationChangeMap
+	if config.Get().ExternalServices.Istio.ValidationChangeDetectionEnabled {
+		changeMap = r.kialiCache.ValidationConfig().Items()
+	}
 
 	// validation requires cross-cluster service account information.
-	vInfo, err := r.validationsService.NewValidationInfo(ctx, r.clusters)
+	vInfo, err := r.validationsService.NewValidationInfo(ctx, r.clusters, changeMap)
```
Comment (nrfox) [inline controller/validations.go:126]: The interface here is a little confusing to me. You need to pass in a `changeMap` to `NewValidationInfo` then you pass `vInfo` to `Validiate(..., vInfo)` and then you check if `Validate(..., vInfo)` returns `nil` to determine if validations we're skipped or not?

We have the previous `changeMap` already and we can get the new `changeMap` from `vInfo`. Can we just compare the two change maps and call `Validate` conditionally if they haven't changed rather than having to pass the `changeMap` into validate and then check if the result is `nil`? Generally when functions return `nil` even when `err == nil` it results in nil pointer derefs down the road.

Some version of:
```
if oldChangeMap[cluster].hash != newChangeMap[cluster].hash {
  Validate(ctx, cluster, vInfo)
} else{
  No changes
}
```

File: models/workload.go [hunk 7]
```diff
@@ -172,6 +172,13 @@ type WorkloadListItem struct {
 
 	// Names of the waypoint proxy workloads, if any
 	WaypointWorkloads []string `json:"waypointWorkloads"`
+
+	// ValidationKey is a pre-calculated key string: "cluster:namespace:name"
+	ValidationKey string
```
Comment (nrfox) [inline models/workload.go:177]: Can this be an object similar to `IstioValidationKey` to reduce the risk of getting the formatting right every time with the string? It looks like the comment is already out of date since the key contains `Kind` as well. I don't think any of the fields (cluster,namespace,name,kind) allow `:` in the values but if they did that would also cause issues.

File: config/config.go (hunk 5 above)
Comment (jshaughn) [reply config/config.go:328]: nice catch!

File: business/references/workloadgroup_references.go [hunk 8]
```diff
@@ -12,7 +12,7 @@ import (
 type WorkloadGroupReferences struct {
 	WorkloadGroups        []*networking_v1.WorkloadGroup
 	WorkloadEntries       []*networking_v1.WorkloadEntry
-	WorkloadsPerNamespace map[string]models.WorkloadList
+	WorkloadsPerNamespace map[string]models.Workloads
```
[the remark this answers is not in the document]
Comment (jshaughn) [reply business/references/workloadgroup_references.go:15]: Yes, it generated massive churn but also a lot of savings.  After looking closely I realized there really wasn't any need to be using WorkloadList, and we were doing a lot of work and object creation when generating them.

File: business/workloads.go [hunk 9]
```diff
@@ -281,9 +282,10 @@ func (in *WorkloadService) GetWorkloadList(ctx context.Context, criteria Workloa
 		return *workloadList, err
 	}
 
+	config := config.Get()
```
[the remark this answers is not in the document]
Comment (jshaughn) [reply business/workloads.go:285]: +1, I just realized while working on the "Get()" PR that the business services already offer up the config.  I'll make the change...

File: config/config.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (jshaughn) [reply config/config.go]: I'm going to leave the config option as a fail-safe, just in case we missed something and in the field someone needs a way to disable it.  But, I'll close my operator PR that makes it public.  We'll leave it undocumented.  If we get comfortable with it then we can kill off the option in the future.

File: controller/validations.go (hunk 6 above)
Comment (jshaughn) [reply controller/validations.go:126]: I agree, it's messy and not a good idea to have a nil return driving the logic here.  But I don't really want the caller dealing with the changeMap in any way other than providing and storing it.  So, how about if we do sort of a "Go-ish thing, and return a bool indicating whether or not we actually performed validation, or whether it was skipped due to no changes?

I'll also improve the function docs a bit.  Let me know what you think.

File: models/workload.go (hunk 7 above)
Comment (jshaughn) [reply models/workload.go:177]: I'm not sure I want to make this an Object, the idea is to pre-calculate an identifying string one time when the workload is pulled in.  It will not be parsed, it's only used as the key in the changeMap to identify this workload in the future.  I'm fairly sure there is only one workload with the cluster:namespace:name combo but if you think it needs to be more complex I guess we could add to it, or perform a hash of various info.

`Kind` is not currently used in this identifier, it's set as described in `WorkloadsService.fetchWorkloadsFromCluster`.  Maybe you saw the keys being generated for the Istio config?  Those are not current pre-calculated, and they do have a hacky "Kind" that I made up.

**Comment by jshaughn** [comment]
@hhovsepy @nrfox thanks for feedback, pulled Hayk's suggestion, pushed some changes, and closed the operator PR...

File: models/workload.go (hunk 7 above)
Comment (nrfox) [reply models/workload.go:177]: Then having a some kind of method to construct the key would be nice. Something like `validations.ValidationWorkloadKey(cluster, ...)`. Ideally workload parsing would know nothing about the internals of validations since validations are independent of parsing a workload but it's currently a mix. We can keep it as is for the time being.

File: controller/validations.go (hunk 6 above)
Comment (nrfox) [reply controller/validations.go:130]: I still think the change detection should happen outside of `Validate` but I'm fine with keeping it as is.

File: business/istio_validations.go [hunk 10]
```diff
@@ -230,54 +301,151 @@ func (in *IstioValidationsService) Validate(ctx context.Context, cluster string,
...
+	change := false
+	cluster := vInfo.clusterInfo.cluster
+
+	// loop through the services and gather up their resourceVersions
+	for _, s := range vInfo.clusterInfo.registryServices {
+		change = vInfo.update("SV", cluster, s.Attributes.Namespace, s.Attributes.Name, s.ResourceVersion) || change
+	}
+
+	// loop through the config and gather up their resourceVersions
+	config := vInfo.clusterInfo.istioConfig
```
Comment (nrfox) [inline business/istio_validations.go:366]: FWIW if you want to work with a generic kube object you can use `runtime.Object` and convert from there with something like: https://pkg.go.dev/k8s.io/apimachinery@v0.32.2/pkg/api/meta#Accessor to access fields common to all kube objects. Not sure it would help here though because of the way `istioConfig` is structured where each type has its own field.

**Review by nrfox — APPROVED** [review]

**Comment by nrfox** [comment]
@jshaughn can we keep #8007 open? I don't think this PR should close that issue. Not all of the outstanding tasks have been addressed and it's yet to be seen if this approach will provide a significant enough perf gain to close out that issue.

**Comment by nrfox** [comment]
> '{"level":"error","ts":"2025-03-11T16:17:30Z","msg":"Reconciler error","controller":"validations-controller","object":{"name":"queue","namespace":"queue"},"namespace":"queue","name":"queue","reconcileID":"0dba47cd-7abd-4957-ae91-a1c2fb827706","error":"validations have been updated since reconciling started. Requeuing validation","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/home/fedora/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/home/fedora/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/home/fedora/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}'

This is because of this:

https://github.com/kiali/kiali/blob/05fc8c3917472bce3b8c36acf8050daa7b240646/controller/validations.go#L136-L138

If another thread performs validations and updates the validations cache, then the validations need to start over so as not to overwrite the new changes with old changes.

I don't think it's related to this PR.

File: controller/validations.go (hunk 6 above)
Comment (jshaughn) [reply controller/validations.go:130]: OK, now I think I see more where you are coming from...  I agree that it could be nice if the controller could decide whether to perform the validation, or not, depending on whether it optionally already performed change detection.  The issue is that to perform the change detection you need to gather up all of the objects for the validation.  Because that's built into the Validate logic, it would be a little more disruptive to pull that out.  It's doable, maybe even cleaner, but I'd like to stop short of that, at least for now.

File: models/workload.go (hunk 7 above)
Comment (jshaughn) [reply models/workload.go:177]: Not unlike my above comment, I like the cleanliness and separation of concern.  But to some degree that ship sailed.  We have a bunch of calculated information hanging off of the Workloads.  I mean, WorkloadListItem is horrible, it's actually a server-side construct designed to support a UI list page.  Still, in another PR maybe we can improve this validation key stuff, and not keep piling on.  Like you say, we could at least maybe extract the key generation logic, if not the storage location.

File: business/istio_validations.go (hunk 10 above)
Comment (jshaughn) [reply business/istio_validations.go:366]: I think this is OK as-is.

**Comment by hhovsepy** [comment]
> If another thread performs validations and updates the validations cache, then the validations need to start over so as not to overwrite the new changes with old changes.
> 
> I don't think it's related to this PR.

Yes, I agree, just noticed recently while testing this PR.
