### PR TITLE
[AI] Fix panic in get_mesh_graph

### LINKED ISSUE #9363: [AI][Tool][Panic] get_mesh_ghrah throw panic when the namespace not exist
### Describe the bug

Get_mesh_ghrah throw panic when the namespace not exist

### Expected Behavior

Return a string error telling that namespace not exist

### What are the steps to reproduce this bug?

Call the tool with a random namespace

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

- Fix panic in get_mesh_graph
- Add get_mesh_graph_tests

### Steps to test the PR

```bash
curl -X POST "$KIALI_URL/api/chat/mcp/get_mesh_graph" \
  -H "Content-Type: application/json" \
  -d '{
    "namespace": "bookinfo"
  }'
```

```bash
curl -X POST "$KIALI_URL/api/chat/mcp/get_mesh_graph" \
  -H "Content-Type: application/json" \
  -d '{
    "namespaces": "bookinfo,default",
    "graphType": "versionedApp",
    "rateInterval": "10m",
    "clusterName": "Kubernetes"
  }'
```

### Automation testing

If applicable, explain the case scencarios covered by **unit / integration / e2e** tests created for this PR.

### Issue reference

Fixes #9363

### CODE REVIEW

**Comment by aljesusg** [comment]
Sorry Josune. I addressed this in my PR with https://github.com/kiali/kiali/pull/9376/changes#diff-90b29dc66934f789a10015546ecac5d4071de65ffbe888f9e9eca4874229fd0cR63 I think is more accurate that is using the internal way to validate if exist and if the user has access to the namespace.

You can pull that code to this PR if you prefer

**Comment by josunect** [comment]
> [https://github.com/kiali/kiali/pull/9376](https://github.com/kiali/kiali/pull/9376/changes#diff-90b29dc66934f789a10015546ecac5d4071de65ffbe888f9e9eca4874229fd0cR63)

I will rebase with https://github.com/kiali/kiali/pull/9376

File: ai/mcp/get_mesh_graph/get_mesh_graph.go [hunk 1]
```diff
@@ -45,40 +45,72 @@ func Execute(r *http.Request, args map[string]interface{}, business *business.La
...
+
 	// Parse arguments: allow either `namespace` or `namespaces` (comma-separated string)
 	namespaces := make([]string, 0)
+	var invalidAccess []string
 	seen := map[string]struct{}{}
-	if v := mcputil.GetStringArg(args, "namespaces"); v != "" {
-		for _, ns := range strings.Split(v, ",") {
+
+	// Collect namespace names from both possible parameters
+	namespacesArg := mcputil.GetStringArg(args, "namespaces", "namespace")
```
Comment (aljesusg) [inline ai/mcp/get_mesh_graph/get_mesh_graph.go]:
```suggestion
	namespacesArg := mcputil.GetStringArg(args, "namespaces")
```

**Comment by josunect** [comment]
> LGFM just a minor one due we removed the namespace attr

Good catch! Thanks
