### PR TITLE
[Scale] Revise kiali_health_status metric approach

### LINKED ISSUE #9422: Multiple issues with health precompute metrics (`kiali_health_status`)
### Describe the bug
[Kiali 2.22](https://kiali.io/news/release-notes/#2220) introduced the `health pre-compute` feature:

* https://github.com/kiali/kiali/issues/8900
* https://github.com/kiali/kiali/pull/9082

based on KEP https://github.com/kiali/kiali/blob/482329dbe6e74d741240f64dceee8fd33647aa24/design/KEPS/health-precompute/proposal.md#prometheus-health-metrics

While a nice speed improvement there are multiple issues:

1. The metric `kiali_health_status` is EXTREMELY high cardinality. Our mid-size clusters have more than 5000 or 8000 series just for this metric. **Export of these metrics totally needs to be opt-in / optional as a first measure!**

2. There is no removal of old time series from the metrics registry. This is (like) a memory leak causing more and more time series originating from old apps and things to still be exported, until Kiali is restarted. See code at https://github.com/kiali/kiali/pull/9082/changes#diff-429f67069b897058c4a238724c5eff154bb4e2cf7db91e1aff770e8b0d056f80R650-R666 lacking any cleanup / housekeeping. This is how some workload movement then looks like in sheer time-series count:

Image

3. These metrics are exported per replica of Kiali, even though they actually are cluster-wide. This again multiplies  the number of time series with the number of replicas.

### Environment
- **Kiali version: 2.22 **
- **Istio version: 1.29.1 **
- **Kubernetes impl: AWS EKS ** 
- **Kubernetes version: 1.34 ** 
- **Other notable environmental factors: **

### PR DESCRIPTION
**Pull request by jshaughn**
Fixes #9422 

Kiali v2.22 introduced the health cache and the ability to generate the `kiali_health_status` metric. This metric is the foundation for future work that can provide granular  health history for charting, alerting, etc.

The initial meric approach was not particularly efficient, and was also opt-out. problems with the new metric are documented in the attached issue.

This PR reimplements the metric approach, and should result in a series cardinality reduction > 80%, as it is now a single series per entity, whereas previously it was a series per status per entity (5N), and N/A entity health is no longer stored.

- health_status metric can now be enabled independently of Kiali's legacy perf metrics (which are opt-out).
  - it is disabled by default (opt-in)
- much lower cardinality: a single gauge series per entity with non-NA status (entity=app,service,workload,namespace)
- kiali never sets health for an an entity with NA health, And stops scraping entities that change from active health to NA for a configurable number of evaluations.

Note: the old metric series' will exist until purged.

Testing
======
For information about the metric you can look at the KEP updates in the PR.

The health_status metric is disabled by default. You should not see `kiali_health_status` series in Prom.
 - note, if you are using an existing install running kiali, you will see the metric. It will have the `status` attribute. This attribute will not exist (will be unset) in the PR version.

To enable, update the Kiali CR `server.observability.metrics.health_status.enabled: true`. This should start the flow of health status.

You can inspect Prom and look for the new gauge entries: `kiali_health_status`. There should be a time series for every entity (service, workload, app, namespace) with a non-NA health status.
- note, again, if you have the old metrics, narrow the query to `kiali_health_status{pod="pr-kiali-pod-name"}`

If you like, run bookinfo, via Kiali add fault injection to say, the ratings service.  watch the graph as things degrade and then fail. Then remove the FI and watch it return back top healthy. Then go to the prom interface and try the graph option for `kiali_health_status{health_type="app",name="reviews"}`. You should see the history of status change.

### CODE REVIEW

**Comment by jshaughn** [comment]
This should be backported to v2.22.

**Comment by frittentheke** [comment]
> Note: the old metric series' will exist until purged.
You mean purged from Prometheus?

Because your code does not seems to address the removal of series for which there is no health (`N/A`) available anymore ... https://github.com/kiali/kiali/pull/9428/changes#diff-429f67069b897058c4a238724c5eff154bb4e2cf7db91e1aff770e8b0d056f80R679-R688 ?

But reading https://github.com/kiali/kiali/pull/9428/changes#diff-6649ca29240a1b7e8ce35363d9264310d58d253d480fb5571286444af629e38bR115-R163 I wonder if this provides the ultimate housekeeping (removing non-exisiting keys, be it workload that disappeared OR namespaces)

**Comment by jshaughn** [comment]
> be it workload that disappeared OR namespaces

This PR does not handle the disappearance of entire namespaces as Kiali doesn't currently keep a history of accessible namespaces, it cares about its currently accessible namespaces.

So, there is a definite inefficiency for environments that may be churning namespaces. Let me see if there is a reasonably easy way to handle this scenario.

UPDATE: I added handling for dropped clusters and/or namespaces. So, I think series deletion is now robust.

File: business/health_cache.go [hunk 1]
```diff
@@ -135,6 +137,15 @@ func (m *healthMonitor) RefreshHealth(ctx context.Context) error {
 		totalErrors += errCount
 	}
 
+	// To avoid accidental wiping of series, we only perform the reconcile after a successful refresh
```
Comment (jmazzitelli) [inline business/health_cache.go]: **BUG-1: Empty cluster list skips metric reconciliation**

When `GetClusters()` returns empty (line 117), `RefreshHealth` returns `nil` before reaching this `ReconcileDroppedClusters` block. If a previously-tracked cluster disappears from the cache (misconfiguration, transient cache issue), its `kiali_health_status` series linger indefinitely because reconciliation never runs.

The comment here says "we only perform the reconcile after a successful refresh" but the empty-clusters early return is treated as success (`return nil`). Dashboards could show stale healthy-status for removed clusters.

One option: move reconciliation before the early return, or treat empty clusters as a signal to reconcile all tracked clusters as dropped.

**Severity: Important**

File: business/health_cache.go [hunk 2]
```diff
@@ -267,43 +285,70 @@ func (m *healthMonitor) refreshNamespaceHealth(ctx context.Context, layer *Layer
 
 	m.cache.SetHealth(cluster, namespace, cachedData)
 
-	// Export health status metrics if enabled
-	if m.conf.Server.Observability.Metrics.Enabled {
+	// Export health status metrics if enabled (independent of general performance metrics)
+	if m.conf.Server.Observability.Metrics.HealthStatus.Enabled {
```
Comment (jmazzitelli) [inline business/health_cache.go:301]: **BUG-2: Total health failure for a namespace leaves Prometheus gauges stale**

When all three health computations fail (line 260-261), `refreshNamespaceHealth` returns an error before reaching this `exportHealthStatusMetrics` call. No `Observe` or `ReconcileNamespace` calls are made for that namespace.

Meanwhile, the failed namespace is still added to `visitedNamespaces` (line 221 in `refreshClusterHealth`), so `ReconcileDroppedNamespacesForCluster` won't touch it either.

Result: existing gauge values persist with no path to staleness detection. Repeated failures mean dashboards/alerts show last-known health indefinitely.

This may be intentional (conservative: don't delete data during transient failures). If so, worth a comment explaining the design choice. If not, consider calling `ReconcileNamespace` with an empty `seenKeys` on total failure to advance entities toward deletion.

**Severity: Important**

File: business/health_cache.go [hunk 3]
```diff
@@ -267,43 +285,70 @@ func (m *healthMonitor) refreshNamespaceHealth(ctx context.Context, layer *Layer
...
 	serviceHealth models.NamespaceServiceHealth,
 	workloadHealth models.NamespaceWorkloadHealth,
 ) {
-	// Export app health metrics using pre-calculated status
+	if !m.conf.Server.Observability.Metrics.HealthStatus.Enabled {
+		return
+	}
+
+	// Track seen entities for reconciliation (to detect entities that disappeared)
+	seenKeys := make(map[entityKey]bool)
```
Comment (jmazzitelli) [inline business/health_cache.go:321]: **TST-1: No integration test for `exportHealthStatusMetrics`**

`exportHealthStatusMetrics` is the integration glue between health data and the exporter — it builds `seenKeys`, extracts status strings, computes namespace aggregate, and calls `ReconcileNamespace`. A wrong `seenKeys` construction or incorrect status extraction would not be caught by the exporter unit tests (which call `Observe`/`Reconcile` directly).

Particularly, the namespace-aggregate path (lines 341-348) using `AggregateNamespaceStatus` + `WorstStatus` is untested end-to-end.

**Suggested:** Add an integration-style test with minimal `NamespaceAppHealth`/`NamespaceServiceHealth`/`NamespaceWorkloadHealth` maps asserting correct Prometheus gauge values and reconciliation behavior.

**Severity: Important**

File: prometheus/internalmetrics/internal_metrics.go [hunk 4]
```diff
@@ -645,23 +644,45 @@ func IncrementHealthCacheMisses(healthType HealthType) {
...
-			labelName:         name,
-			labelHealthStatus: status,
-		}).Set(value)
+// HealthStatusValue converts a health status string to a numeric value.
+// Returns (value, ok) where ok is false for "NA" status (should not be exported).
+// Value mapping: 0=Healthy (best), 1=Not Ready, 2=Degraded, 3=Failure (worst).
+func HealthStatusValue(status string) (float64, bool) {
+	switch status {
+	case "Healthy":
+		return 0.0, true
```
Comment (jmazzitelli) [inline prometheus/internalmetrics/internal_metrics.go:653]: **TST-2: `"Not Ready"` status value never asserted in tests**

The `"Not Ready"` → `1.0` mapping here is part of the public contract but is never exercised in `health_status_exporter_test.go`. Other status values (`Healthy`/`Degraded`/`Failure`) are all asserted.

**Suggested:** Add `e.Observe(cluster, ns, HealthTypeApp, name, "Not Ready")` followed by `require.InDelta(t, 1.0, v, 1e-9)`.

**Severity: Important**

File: business/health_cache.go [hunk 5]
```diff
@@ -267,43 +285,70 @@ func (m *healthMonitor) refreshNamespaceHealth(ctx context.Context, layer *Layer
...
+		seenKeys[NewEntityKey(cluster, namespace, internalmetrics.HealthTypeWorkload, wkName)] = true
 	}
+
+	// Export namespace aggregate health (reuse existing aggregation function)
+	namespaceAggregate := models.AggregateNamespaceStatus(&appHealth, &serviceHealth, &workloadHealth)
+	namespaceStatus := "NA"
+	if namespaceAggregate != nil && namespaceAggregate.WorstStatus != "" {
+		namespaceStatus = namespaceAggregate.WorstStatus
+	}
+	m.healthStatusExp.Observe(cluster, namespace, internalmetrics.HealthTypeNamespace, namespace, namespaceStatus)
```
Comment (jmazzitelli) [inline business/health_cache.go:359]: **TST-3: `HealthTypeNamespace` never tested**

`HealthTypeNamespace` is introduced in this PR but never appears in test assertions. Only `HealthTypeApp`, `HealthTypeService`, and `HealthTypeWorkload` are exercised in `health_status_exporter_test.go`. The namespace type has unique semantics (`name` == namespace string) worth covering.

**Severity: Important**

File: business/health_status_exporter.go [hunk 6]
```diff
@@ -0,0 +1,238 @@
...
+
+import (
+	"sync"
+
+	"github.com/kiali/kiali/config"
+	"github.com/kiali/kiali/prometheus/internalmetrics"
+)
+
+// entityKey uniquely identifies a health entity for tracking grace state between refresh cycles.
+type entityKey struct {
```
Comment (jmazzitelli) [inline business/health_status_exporter.go:11]: **STY-1: `entityKey` fields not alphabetically sorted**

Per project convention (sort names in Go structs for touched code), fields should be ordered: `cluster`, `healthType`, `name`, `namespace`. Currently: `cluster`, `namespace`, `healthType`, `name`. The keyed literal in `NewEntityKey` (lines 20-24) should match.

**Severity: Minor**

File: business/health_status_exporter.go [hunk 7]
```diff
@@ -0,0 +1,238 @@
...
+		return
+	}
+	internalmetrics.DeleteHealthStatusForItem(key.cluster, key.namespace, key.healthType, key.name)
+	delete(e.seriesPresent, key)
+}
+
+// maxConsecutiveNA returns the configured streak length of NA or missing refresh cycles
+// before deleting a series. Values <= 0 use the default (3).
+func (e *HealthStatusExporter) maxConsecutiveNA() int {
+	n := e.conf.Server.Observability.Metrics.HealthStatus.MaxConsecutiveNA
```
Comment (jmazzitelli) [inline business/health_status_exporter.go:67]: **IMP-1: `maxConsecutiveNA()` default duplicates config default**

The fallback `return 3` here duplicates the default set in `config.NewConfig()` (`MaxConsecutiveNA: 3`). If the default changes in config but not here, they'd drift. Consider extracting to a const or adding a comment referencing the config default.

Also, operators may assume `max_consecutive_na: 0` means "no grace / delete immediately" when it actually means "use default 3." Worth documenting in the KEP or config comments.

**Severity: Minor**

File: business/health_cache.go (hunk 1 above)
Comment (jshaughn) [reply business/health_cache.go]: This is legit but very unlikely because it is the case where is monitoring 0 clusters, and I'm not even sure that ever happens. But I'll make a change. I think we can maybe make the logic a little more safe overall.

File: business/health_cache.go (hunk 2 above)
Comment (jshaughn) [reply business/health_cache.go:301]: hmm, I guess this is legit, although another pretty deep corner case. I'll fix it.

File: business/health_cache.go (hunk 3 above)
Comment (jshaughn) [reply business/health_cache.go:321]: This is probably worthy of a follow-up. I'm not going to do it in this PR. This is not the easiest thing to set-up in cypress.

File: prometheus/internalmetrics/internal_metrics.go (hunk 4 above)
Comment (jshaughn) [reply prometheus/internalmetrics/internal_metrics.go:653]: Added.

File: business/health_cache.go (hunk 5 above)
Comment (jshaughn) [reply business/health_cache.go:359]: Added.

File: business/health_status_exporter.go (hunk 6 above)
Comment (jshaughn) [reply business/health_status_exporter.go:11]: Fixed.

File: business/health_status_exporter.go (hunk 7 above)
Comment (jshaughn) [reply business/health_status_exporter.go:67]: I think it's clear in the config doco.

File: business/health_cache.go (hunk 3 above)
Comment (jshaughn) [reply business/health_cache.go:321]: https://github.com/kiali/kiali/issues/9449
