### PR TITLE
Fix app and service minigraph on multicluster

### LINKED ISSUE #6062: Multicluster - Details page Graph section
Currently the App/Workload/Service details page's Graph section does not send cluster param to backend for querying.

RFE: But it needs to send cluster param and do queries for cluster.

Screenshot from 2023-04-26 10-32-49

### PR DESCRIPTION
**Pull request by leandroberetta**
Resolves #6062.

Given the following graph topology:

image

Service's minigraph for ratings on west cluster

image

Application's minigraph for ratings on west cluster

image

Application's minigraph for reviews on west cluster

image

Service's minigraph for reviews on west cluster

image

### CODE REVIEW

File: frontend/src/services/GraphDataSource.ts [hunk 1]
```diff
@@ -267,6 +267,10 @@ export default class GraphDataSource {
       }
     });
 
+    if (fetchParams.node && fetchParams.node.cluster) {
```
Comment (jshaughn) [inline frontend/src/services/GraphDataSource.ts:270]:
```suggestion
    if (fetchParams.node?.cluster) {
```

**Review by jshaughn — APPROVED** [review]
Looks good, I added one optional code-style suggestion, but the feature is fixed!

**Review by jshaughn — APPROVED** [review]
Re-approve after minor edit.
