### PR TITLE
Make expires in optional for OpenId authentication

### LINKED ISSUE #2954: OpenID authentication strategy should not require "expires_in" in the callback
As noted in comment this comment of another issue: https://github.com/kiali/kiali/issues/2925#issuecomment-650837094, OpenID is not working properly if the IdP does not include the `expires_in` URL parameter when invoking the callback url. This leads to a failed authentication.

[Section 3.2.2.5 of the OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse) states that `expires_in` parameter is *optional*. Thus, authentication should succeed even if it's not present.

### PR DESCRIPTION
**Pull request by cfcosta**
Closes #2954

Fix a problem where some authentication providers (such as Okta) do not provide an expiration date for the token. It is optional on the spec, so we make it optional here as well with a value of **1 day**.

### CODE REVIEW

**Comment by mikolajwrzesinski** [comment]
I think this issue should be solved differently. As noted in https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse `expires_in` is the expiry time of the Access Token, not ID Token. To validate `id_token` you need to analize `exp` claim of the token.

**Comment by cfcosta** [comment]
> I think this issue should be solved differently. As noted in https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse `expires_in` is the expiry time of the Access Token, not ID Token. To validate `id_token` you need to analize `exp` claim of the token.

Thanks for the feedback! I need to investigate a bit further to make sure, but I think you're right.

@israel-hdez what do you think?

**Comment by cfcosta** [comment]
@mikolajwrzesinski commited a draft on how that should look like, what do you think? I still need to test it a little bit more to be confident, but should be ok.

**Comment by jmazzitelli** [comment]
don't forget to make sure the openid integration test passes - making necessary updates to it as appropriate: https://github.com/kiali/kiali-operator/tree/master/molecule/openid-test

**Comment by cfcosta** [comment]
@jmazzitelli will do it.

File: handlers/authentication.go [hunk 1]
```diff
@@ -285,9 +279,37 @@ func performOpenIdAuthentication(w http.ResponseWriter, r *http.Request) bool {
...
+			RespondWithDetailedError(w, http.StatusBadRequest, "Token exp claim is present, but invalid.", err.Error())
+			return false
+		}
+
+		expiresOn = time.Now().Add(time.Second * time.Duration(expiresInNumber))
+	}
 
+	// Then we check the expiration date for the access on the access token
+	// We give priority to it because it is what we use to access the cluster,
+	// so if it is valid we are ok.
```
Comment (israel-hdez) [inline handlers/authentication.go:299]: @mikolajwrzesinski has already noted that the OpenId spec tells that the `expires_in` parameter is tied to the `access_token` (see https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse).

For OpenID we are *not* using the `access_token`, but the `id_token`. We can safely ignore `expires_in` parameter. So, this block should be removed.

File: handlers/authentication.go [hunk 2]
```diff
@@ -285,9 +279,37 @@ func performOpenIdAuthentication(w http.ResponseWriter, r *http.Request) bool {
...
 	}
 
-	// Create business layer using the received id_token
-	expiresOn := time.Now().Add(time.Second * time.Duration(expiresInNumber))
+	// Set a default value for expiration date
+	expiresOn := time.Now().Add(time.Second * time.Duration(defaultSessionDuration))
+
+	// We check for the expiration date from the claim
+	if expClaim := idTokenClaims["exp"].(string); expClaim != "" {
+		expiresInNumber, err := strconv.Atoi(expClaim)
```
Comment (israel-hdez) [inline handlers/authentication.go:287]: Can you double-check this?
AFAIK, the `exp` claim is a Unix timestamp. If this is true, you should take the value as is (as the expiration time), rather than using it as a duration.

File: handlers/authentication.go (hunk 1 above)
Comment (cfcosta) [reply handlers/authentication.go:299]: Since we do use the `access_token` to to the requests to kubernetes, wouldn't it be the case where the expiration provided on `expires_in` be more reliable than the exp on the id_token?

Comment (israel-hdez) [reply handlers/authentication.go:299]: The `id_token` is the one used for OpenID (see the checks at https://github.com/kiali/kiali/pull/2981/files#diff-7b14eebb8414820b40c718efcf921867R244-R249). The `access_token` is ignored in this case. So, `expires_in` is not that reliable.

For OpenShift it is different. In OpenShift, we DO use the `access_token` and it's better to use `expires_in`. But for this PR, we should move to using the `exp` claim.

Comment (israel-hdez) [reply handlers/authentication.go:299]: See also an already fixed issue: https://github.com/kiali/kiali/issues/2925. It's mentioned that some IdPs won't send an `access_token`.

File: handlers/authentication.go (hunk 2 above)
Comment (cfcosta) [reply handlers/authentication.go]: Should be correct now.

**Comment by cfcosta** [comment]
@israel-hdez can you verify it again?

**Comment by cfcosta** [comment]
Build has failed, looking at why.

**Comment by cfcosta** [comment]
@israel-hdez this latest commit should take care of the panic.

**Comment by mikolajwrzesinski** [comment]
Thank you guys! v1.21 works with Keycloak

**Comment by jshaughn** [comment]
@mikolajwrzesinski Excellent news!
