### PR TITLE
[Ambient] Fix Control Plane Ambient badge logic

### LINKED ISSUE #8867: [ambient] Detect isAmbient by CP
### Describe the bug

When Kiali detects any ztunnel it shows all the control planes as Ambient, but they might not be Ambient for all the Control planes. 

### Expected Behavior

Detect Ambient by control plane and not globally.

### What are the steps to reproduce this bug?

1. Install Kiali multi cluster
2. One CP is Ambient 
3. Not the other

Kiali is showing Ambient badge for both clusters:

Image

### Environment
*Learn about how to determine versions [here](https://kiali.io/docs/faq/general/#how-do-i-determine-what-version-i-am-running).*

- **Kiali version:**
- **Istio version:**
- **Kubernetes impl:** 
- **Kubernetes version:** 
- **Other notable environmental factors:**

### PR DESCRIPTION
**Pull request by josunect**
### Describe the change

- For each control plane, check if has Ambient enabled: By checking the value `PILOT_ENABLE_AMBIENT=true` in the deployment. That should work for different scenarios, independently of revisions, different meshes and multi cluster. Ref. https://istio.io/latest/docs/ambient/upgrade/helm
- Modify the hack install script for Ambient multi cluster to disable Ambient in the remote cluster: 
`hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true --keycloak-limit-memory 5Gi --keycloak-requests-memory 2Gi -am true -c2a false`

### Steps to test the PR

- Run: `hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true --keycloak-limit-memory 5Gi --keycloak-requests-memory 2Gi -am true -c2a false`
- Validate there is no ztunnel daemonset/pod in the west cluster
- CP Card in west cluster should not be Ambient: 

image

- Run: `hack/run-integration-tests.sh --test-suite frontend-multi-primary --setup-only true --keycloak-limit-memory 5Gi --keycloak-requests-memory 2Gi -am true`
- Validate there is a ztunnel daemonset/pod in the west cluster
- CP Card in west cluster should be Ambient: 

image

### For the same cluster
- In a single cluster Ambient mesh, create a new Istio revision (Not Ambient): 
`kubectl create ns istio-canary`
`helm upgrade --install istiod-canary istio/istiod -n istio-canary --set revision=canary`
- That namespace should not show as Ambient: 
image

### Automation testing

Added e2e tests

### Issue reference

Fixes #8867

### CODE REVIEW

File: business/namespaces.go [hunk 1]
```diff
@@ -401,3 +407,42 @@ func (in *NamespaceService) HasMeshAccess(ctx context.Context, cluster string) b
...
+func (in *NamespaceService) validateControlPlaneNamespaceAmbient(ctx context.Context, ns *models.Namespace, cluster string, ztunnelDaemonSets []apps_v1.DaemonSet) {
+	// Get the revision that manages this namespace
+	nsRevision := istio.GetRevision(*ns)
+	if nsRevision == "" {
+		// No revision means namespace is not in the mesh
+		nsRevision = models.DefaultRevisionLabel
+	}
+
+	if cluster != ns.Cluster {
+		ns.IsAmbient = false
```
Comment (jshaughn) [inline business/namespaces.go]: I'm not sure this should really change the `IsAmbient` flag for a namespace on a different cluster. Although it's unlikely this will ever execute as this call is unlikely to ever be made with mismatching cluster values. Not a blocker.

File: cache/cache.go [hunk 2]
```diff
@@ -329,6 +332,27 @@ func (in *kialiCacheImpl) GetZtunnelPods(cluster string) []v1.Pod {
 	return podList.Items
 }
 
+func (in *kialiCacheImpl) GetZtunnelDaemonset(cluster string) []appsv1.DaemonSet {
+	kubeCache, err := in.GetKubeCache(cluster)
+	if err != nil {
+		in.zl.Debug().Msgf("Unable to get kube cache when checking for ambient profile: %s", err)
```
Comment (jshaughn) [inline cache/cache.go]: This message duplicates at least one above, I suggest you alter the messages to be unique in some way, so that if we see it we can easily distinguish where it came from.

**Comment by jshaughn** [comment]
To summarize for off-PR discussion.There are two main use cases that result in multiple Istio control planes on the same cluster. One is a revision-based update, such that the Istio control-plane is being upgraded from one version to another. In this case it it typical that the only thing changing is the control plane version, and possibly any mandatory update-related config. This is not really the relevant use-case, as it is unlikely that a new revision would change Ambient modes. The second case is multi-mesh/multi-tenant. Where multiple control planes are running. likely divided by Discovery Selectors. It is possible that the control planes may differ in ambient support.

Note that at the time of this PR, Kiali's MM/MT support is evolving. Historically, a single Kiali was concerned only with a single mesh. This is still the preferred deployment model, although limited MM support is being added (see https://github.com/kiali/kiali/issues/8329)

**Comment by josunect** [comment]
> I don't think MC is the primary use case, but it's working. Overview page looks good: image
> 
> I'm not sure about Mesh Page. Maybe it's the test setup but should there be an edge to West's control plane? image
> 
> Single cluster Overview looks good: image
> 
> I think single cluster Mesh page is OK: the canary istiod has no edge to ztunnel: image
> 
> Code looks good. I'll approve but let me know about that multi-cluster mesh page.

The edge should be from Kiali to the west Istiod? 
I was comparing with the multi cluster (Not Ambient) and this is what I see: 
image

From this picture it looks like the data plane is missing for some reason? 

But it looks like the edge to Kiali is missing as well...

**Comment by hhovsepy** [comment]
Did tested a corner case, when on a single cluster there are 2 ambient meshes and one sidecar.
In the Mesh page, the edges between ztunnels and Istiods are all-to-all, and change by each refresh:
Screenshot From 2025-11-12 09-18-34
Shouldn't each ztunnel reference to it's own Istiod, by a revision ?

**Comment by josunect** [comment]
> Did tested a corner case, when on a single cluster there are 2 ambient meshes and one sidecar. In the Mesh page, the edges between ztunnels and Istiods are all-to-all, and change by each refresh: Screenshot From 2025-11-12 09-18-34 Shouldn't each ztunnel reference to it's own Istiod, by a revision ?

Good catch, @hhovsepy 
Maybe the edge could be just to the ztunnel from the same cluster? I didn't see documented that Ambient external ztunnel is supported (Actually, just alpha multi primary is supported at the moment https://istio.io/latest/docs/ambient/install/multicluster/#control-plane-limitations).

**Comment by josunect** [comment]
> > Did tested a corner case, when on a single cluster there are 2 ambient meshes and one sidecar. In the Mesh page, the edges between ztunnels and Istiods are all-to-all, and change by each refresh: Screenshot From 2025-11-12 09-18-34 Shouldn't each ztunnel reference to it's own Istiod, by a revision ?
> 
> Good catch, @hhovsepy Maybe the edge could be just to the ztunnel from the same cluster? I didn't see documented that Ambient external ztunnel is supported (Actually, just alpha multi primary is supported at the moment https://istio.io/latest/docs/ambient/install/multicluster/#control-plane-limitations).

I see, they are in the same cluster. Maybe we can check the revisions or mesh id when there are more than one on the same cluster

**Comment by hhovsepy** [comment]
> 
> I see, they are in the same cluster. Maybe we can check the revisions or mesh id when there are more than one on the same cluster

The scenario is less possible, but yes imo it should be checking the revisions.

**Comment by jshaughn** [comment]
Maybe we should have a meeting to talk about these things but a couple of comments:
- I think I was wrong about expecting an edge between Kiali and the remote Istiod.
- I'm not sure why on the original the remote istiod does not have an attached dataplane node.
  - I'll recreate the test env and see if it makes sense
- ztunnel is a node-level daemon-set. In Hayk's screen shot I would expect to see only one ztunnel node, not two, because we're looking at a one-node cluster, right?
  - Ztunnels don't have revision-based update afaik, they need to upgrade from A to B in one shot.
  - To be honest, I have no idea what our mesh page would look like for ztunnel on a multi-node cluster.

**Comment by hhovsepy** [comment]
My last testing scenario made a confusion, it was not a real world scenario case, so it does not need to be fixed.

**Comment by josunect** [comment]
> Maybe we should have a meeting to talk about these things but a couple of comments:
> 
>     * I think I was wrong about expecting an edge between Kiali and the remote Istiod.
> 
>     * I'm not sure why on the original the remote istiod does not have an attached dataplane node.
>       
>       * I'll recreate the test env and see if it makes sense

Yes, It looks like wrong to me, because there is a dataplane

> 
>     * ztunnel is a node-level daemon-set. In Hayk's screen shot I would expect to see only one ztunnel node, not two, because we're looking at a one-node cluster, right?
>       
>       * Ztunnels don't have revision-based update afaik, they need to upgrade from A to B in one shot.
>       * To be honest, I have no idea what our mesh page would ahow on a multi-node cluster.

Ok, I think, in that case, I can revert my last commit.

**Comment by josunect** [comment]
> Maybe we should have a meeting to talk about these things but a couple of comments:
> 
>     * I think I was wrong about expecting an edge between Kiali and the remote Istiod.
> 
>     * I'm not sure why on the original the remote istiod does not have an attached dataplane node.
>       
>       * I'll recreate the test env and see if it makes sense
> 
>     * ztunnel is a node-level daemon-set. In Hayk's screen shot I would expect to see only one ztunnel node, not two, because we're looking at a one-node cluster, right?
>       
>       * Ztunnels don't have revision-based update afaik, they need to upgrade from A to B in one shot.
>       * To be honest, I have no idea what our mesh page would look like for ztunnel on a multi-node cluster.

@jshaughn I've checked the example, and I think this is correct, as the istiod is not ambient but there are no namespaces with the istio injection label. As soon as you add the injection label in bookinfo, you can see it: 

image

I wonder if the edge from istiod to Kiali shouldn't be there?
